//! Üretilen `.h`/`.rs` dosyalarının imza satırları (ADR-0063 §4):
//!
//! ```text
//! // Generated by Volt 0.1.0 from gpio.volt
//! // regmap-hash: 1f0c3a9d2e4b5a67
//! ```
//!
//! Dosyanın herhangi bir yerinde aranır (üstüne lisans başlığı eklemek
//! ayrışma değildir); ilk eşleşme geçerlidir.

use super::Unsupported;

pub const GENERATED: &str = "// Generated by Volt ";
pub const HASH: &str = "// regmap-hash: ";

/// ADR-0053 başlığı — `regmap-hash`'ten önceki sürümlerin tek izi.
const LEGACY: &str = "generated by Volt HDL";

/// İmza satırlarından okunan bilgi.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Header {
    /// Dosyayı üreten Volt sürümü.
    pub version: String,
    /// Kaynak dosya adı (`gpio.volt`).
    pub source: String,
    /// Beyan edilen `regmap-hash`.
    pub hash: String,
    /// `regmap-hash` satırının bayt aralığı — tanının konumu.
    pub span: (usize, usize),
}

/// İki imza satırını arar; yoksa dosyanın Volt üretimi olmadığı (ya da
/// imzadan önceki bir sürüm olduğu) açıkça söylenir.
pub fn read(text: &str) -> Result<Header, Unsupported> {
    let mut offset = 0;
    let mut lines = text.split_inclusive('\n').peekable();
    while let Some(line) = lines.next() {
        offset += line.len();
        let Some(rest) = line.trim().strip_prefix(GENERATED.trim_start()) else {
            continue;
        };
        let (version, source) = rest.split_once(" from ").unwrap_or((rest, ""));
        // Araya giren boş satırlar biçim farkıdır, imzayı bozmaz.
        while lines.peek().is_some_and(|l| l.trim().is_empty()) {
            offset += lines.next().map_or(0, str::len);
        }
        let Some(next) = lines.peek() else { break };
        let Some(hash) = next.trim().strip_prefix(HASH.trim_start()) else {
            break;
        };
        let hash_start = offset + (next.len() - next.trim_start().len());
        return Ok(Header {
            version: version.trim().to_string(),
            source: source.trim().to_string(),
            hash: hash.trim().to_string(),
            span: (hash_start, hash_start + next.trim().len()),
        });
    }
    Err(unsigned(text))
}

/// İmza yoksa: eski Volt başlığı mı, hiç Volt değil mi?
pub fn unsigned(text: &str) -> Unsupported {
    if text.contains(LEGACY) {
        Unsupported::OldVolt
    } else {
        Unsupported::NotVolt
    }
}

/// Üreticilerin yazdığı iki satır (sonunda `\n`).
pub fn render(version: &str, source: &str, hash: &str) -> String {
    format!("{GENERATED}{version} from {source}\n{HASH}{hash}\n")
}
