//! `volt build --emit=sdc,xdc` (ADR-0054): kısıt dosyalarının yeri,
//! içeriği (create_clock periyodu, set_clock_groups, sync() false path),
//! W0022'nin yalnız istek üzerine verilmesi, E0017 ve JSON artifacts.

use std::path::{Path, PathBuf};
use std::process::Command;

fn volt() -> Command {
    Command::new(env!("CARGO_BIN_EXE_volt"))
}

fn root() -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."))
}

fn ui(rel: &str) -> PathBuf {
    root().join("tests/ui").join(rel)
}

fn temp_dir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("volt-sdc-test-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("temp dizini");
    dir
}

fn build(tag: &str, source: &Path, kinds: &str) -> (PathBuf, std::process::Output) {
    let target = temp_dir(tag);
    let output = volt()
        .args(["build", "--target-dir"])
        .arg(&target)
        .arg(format!("--emit={kinds}"))
        .arg(source)
        .env_remove("VOLT_LANG")
        .output()
        .expect("volt çalışmalı");
    (target, output)
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("{} okunmalı: {e}", path.display()))
}

#[test]
fn single_clock_sdc_has_create_clock_with_period_20_000() {
    let (target, out) = build("single", &ui("pass/73_sdc_single_clock.volt"), "sdc");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "stderr: {stderr}");
    let sdc = read(&target.join("constraints/Uart.sdc"));
    assert!(sdc.starts_with("# Generated by Volt "), "{sdc}");
    assert!(
        sdc.contains("# Source: 73_sdc_single_clock.volt\n# DO NOT EDIT\n"),
        "{sdc}"
    );
    assert!(
        sdc.contains("create_clock -name clk -period 20.000 [get_ports clk]"),
        "{sdc}"
    );
    assert!(!sdc.contains("set_clock_groups"), "{sdc}");
    assert!(
        sdc.contains("set_false_path -from [get_cells {cfg_r_reg*}] -to [get_ports sample]"),
        "{sdc}"
    );
    assert!(stderr.contains("Uart.sdc"), "Output satırı: {stderr}");
    assert!(!stderr.contains("W0022"), "frekans var: {stderr}");
    assert!(!target.join("constraints/Uart.xdc").exists());
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn multi_clock_sdc_has_two_clocks_groups_and_bridge_false_paths() {
    let (target, out) = build("multi", &ui("pass/74_sdc_multi_clock.volt"), "sdc,xdc");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "stderr: {stderr}");
    let sdc = read(&target.join("constraints/Bridge.sdc"));
    assert!(
        sdc.contains("create_clock -name fast_clk -period 10.000 [get_ports fast_clk]"),
        "{sdc}"
    );
    assert!(
        sdc.contains("create_clock -name slow_clk -period 39.722 [get_ports slow_clk]"),
        "{sdc}"
    );
    assert!(sdc.contains("set_clock_groups -asynchronous \\\n    -group [get_clocks {fast_clk}] \\\n    -group [get_clocks {slow_clk}]"), "{sdc}");
    assert!(
        sdc.contains(
            "set_false_path -from [get_cells {go_r_reg*}] -to [get_cells {sync_go_r_stage0_reg*}]"
        ),
        "{sdc}"
    );
    assert!(
        sdc.contains(
            "set_false_path -from [get_cells {ps_toggle_reg*}] -to [get_cells {ps_sync0_reg*}]"
        ),
        "{sdc}"
    );
    assert!(
        sdc.contains("set_multicycle_path 2 -setup -to [get_cells {acc_r_reg*}]"),
        "{sdc}"
    );
    assert!(
        sdc.contains("set_multicycle_path 1 -hold -to [get_cells {acc_r_reg*}]"),
        "{sdc}"
    );
    assert!(!sdc.contains("ASYNC_REG"));
    let xdc = read(&target.join("constraints/Bridge.xdc"));
    assert!(
        xdc.contains(
            "set_property ASYNC_REG TRUE [get_cells {sync_go_r_stage0_reg* sync_go_r_stage1_reg*}]"
        ),
        "{xdc}"
    );
    assert!(
        xdc.contains(
            "set_property ASYNC_REG TRUE [get_cells {ps_sync0_reg* ps_sync1_reg* ps_sync2_reg*}]"
        ),
        "{xdc}"
    );
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn generated_files_pass_syntax_check() {
    let (target, out) = build("syntax", &ui("pass/74_sdc_multi_clock.volt"), "sdc,xdc");
    assert_eq!(out.status.code(), Some(0));
    for name in ["Bridge.sdc", "Bridge.xdc"] {
        let text = read(&target.join("constraints").join(name));
        volt_sdc_emit::syntax_check(&text).unwrap_or_else(|e| panic!("{name}: {e}\n{text}"));
    }
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn vga_example_two_clocks_groups_and_cdc_false_paths() {
    let (target, out) = build("vga", &root().join("examples/vga/vga_top.volt"), "sdc");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "stderr: {stderr}");
    let top = read(&target.join("constraints/VgaTop.sdc"));
    assert_eq!(top.matches("create_clock").count(), 2, "{top}");
    assert!(
        top.contains("create_clock -name sys_clk -period 10.000 [get_ports sys_clk]"),
        "{top}"
    );
    assert!(
        top.contains("create_clock -name pix_clk -period 39.722 [get_ports pix_clk]"),
        "{top}"
    );
    assert!(top.contains("set_clock_groups -asynchronous"), "{top}");
    // frame_buffer: AsyncDualPortRam alt modül örneğinde, önekli.
    assert!(top.contains("set_false_path -from [get_cells {fb/mem_mem_reg*}] -to [get_cells {fb/mem_rd_data_reg*}]"), "{top}");
    // sync() köprüleri: invert (port, yakalama register'ı), done_r (reg), vs_active (let → pix_clk).
    assert!(
        top.contains("-to [get_cells {sync_invert_stage0_reg*}]"),
        "{top}"
    );
    assert!(top.contains("set_false_path -from [get_cells {done_r_reg*}] -to [get_cells {sync_done_r_stage0_reg*}]"), "{top}");
    assert!(top.contains("set_false_path -from [get_clocks pix_clk] -to [get_cells {sync_vs_active_stage0_reg*}]"), "{top}");
    // VgaTiming: @timing(pix_clk >= 25_175.khz) alan frekansıyla karşılanır.
    let timing = read(&target.join("constraints/VgaTiming.sdc"));
    assert!(
        timing.contains("create_clock -name pix_clk -period 39.722 [get_ports pix_clk]"),
        "{timing}"
    );
    assert!(
        !stderr.contains("W0021"),
        "@timing artık W0021 üretmez: {stderr}"
    );
    assert!(!stderr.contains("W0022"), "{stderr}");
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn domain_without_frequency_warns_w0022_only_when_sdc_requested() {
    let dir = temp_dir("w0022");
    let src = "domain Sys { clock = posedge }\nmodule M {\n    in clk : clock @Sys\n    in a : u8\n    out y : u8\n    y = a\n}\n";
    let file = dir.join("m.volt");
    std::fs::write(&file, src).unwrap();

    let plain = volt()
        .args(["build", "--target-dir"])
        .arg(dir.join("b1"))
        .arg(&file)
        .env_remove("VOLT_LANG")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&plain.stderr);
    assert_eq!(plain.status.code(), Some(0), "{stderr}");
    assert!(
        !stderr.contains("W0022"),
        "SDC istenmeden W0022 yok: {stderr}"
    );

    let with_sdc = volt()
        .args(["build", "--target-dir"])
        .arg(dir.join("b2"))
        .arg("--emit=sdc")
        .arg(&file)
        .env_remove("VOLT_LANG")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&with_sdc.stderr);
    assert_eq!(with_sdc.status.code(), Some(0), "{stderr}");
    assert!(stderr.contains("warning[W0022]"), "{stderr}");
    assert!(
        stderr.contains("domain 'Sys' has no frequency; no create_clock emitted for 'clk'"),
        "{stderr}"
    );
    assert!(
        stderr.contains("= help:") && stderr.contains("frequency = 100.mhz"),
        "{stderr}"
    );
    let sdc = read(&dir.join("b2/constraints/M.sdc"));
    assert!(!sdc.lines().any(|l| l.starts_with("create_clock")), "{sdc}");
    assert!(sdc.contains("no create_clock (W0022)"), "{sdc}");
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn check_reports_e0017_for_unsupported_form_exit_1() {
    let out = volt()
        .arg("check")
        .arg(ui("fail/57_timing_unsupported_form.volt"))
        .env_remove("VOLT_LANG")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(1), "{stderr}");
    assert!(stderr.contains("error[E0017]"), "{stderr}");
    assert!(stderr.contains("a delay needs a unit"), "{stderr}");
    assert!(
        stderr.contains("= help: write the delay with a unit: 5.ns, 250.ps or 1.us"),
        "{stderr}"
    );
    assert!(stderr.contains("explain E0017"), "{stderr}");
}

#[test]
fn build_with_e0017_writes_no_constraints() {
    let (target, out) = build("bad", &ui("fail/57_timing_unsupported_form.volt"), "sdc");
    assert_eq!(out.status.code(), Some(1));
    assert!(!target.join("constraints").exists());
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn unit_without_clocked_module_prints_note_exit_0() {
    let dir = temp_dir("noclock");
    let file = dir.join("c.volt");
    std::fs::write(
        &file,
        "module Comb {\n    in a : u8\n    out y : u8\n    y = a\n}\n",
    )
    .unwrap();
    let out = volt()
        .args(["build", "--target-dir"])
        .arg(dir.join("b"))
        .arg("--emit=sdc")
        .arg(&file)
        .env_remove("VOLT_LANG")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "{stderr}");
    assert!(
        stderr
            .contains("Note: no module with a clock port in the unit; --emit=sdc produced nothing"),
        "{stderr}"
    );
    assert!(!dir.join("b/constraints").exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn json_artifacts_list_constraint_files_after_rtl() {
    let target = temp_dir("json");
    let out = volt()
        .args(["build", "--format", "json", "--target-dir"])
        .arg(&target)
        .arg("--emit=sdc,xdc,sdc")
        .arg(ui("pass/73_sdc_single_clock.volt"))
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).expect("JSON zarfı");
    let artifacts: Vec<String> = v["artifacts"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| a.as_str().unwrap().to_string())
        .collect();
    assert_eq!(artifacts.len(), 3, "{artifacts:?} — yinelenen sdc bir kez");
    assert!(artifacts[0].ends_with("Uart.sv"));
    assert!(artifacts[1].ends_with("Uart.sdc"));
    assert!(artifacts[2].ends_with("Uart.xdc"));
    let _ = std::fs::remove_dir_all(&target);
}

#[test]
fn explain_e0017_and_w0022_in_both_languages() {
    for (code, lang, needle) in [
        ("E0017", "en", "Supported forms"),
        ("E0017", "tr", "Desteklenen biçimler"),
        ("W0022", "en", "create_clock needs a period"),
        ("W0022", "tr", "create_clock bir periyot ister"),
    ] {
        let out = volt()
            .args(["explain", code])
            .env("VOLT_LANG", lang)
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&out.stdout);
        assert_eq!(out.status.code(), Some(0), "{code} {lang}");
        assert!(stdout.contains(needle), "{code} {lang}: {stdout}");
    }
}
