//! Sürüm kimliği (ADR-0104): `volt --version`, üretilen SV başlığının
//! `Version:` satırı ve SDC başlığı aynı metni yazar — sürüm ve ikilinin
//! derlendiği commit'in kısaltması, `0.1.0 (a1b2c3d)`. Depo bir git
//! çalışma ağacı değilse (sürüm arşivi) yalnız sürüm.

use std::path::{Path, PathBuf};
use std::process::Command;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("kök")
}

fn git(args: &[&str]) -> Option<String> {
    let out = Command::new("git")
        .args(args)
        .current_dir(root())
        .output()
        .ok()?;
    out.status
        .success()
        .then(|| String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// İkilinin göstermesi gereken metin: build.rs ile aynı kural.
fn expected() -> String {
    let version = env!("CARGO_PKG_VERSION");
    let top =
        git(&["rev-parse", "--show-toplevel"]).and_then(|t| PathBuf::from(t).canonicalize().ok());
    match (top, git(&["rev-parse", "HEAD"])) {
        (Some(top), Some(head)) if top == root() => format!("{version} ({})", &head[..7]),
        _ => version.to_string(),
    }
}

#[test]
fn version_flag_names_the_commit_it_was_built_from() {
    let out = Command::new(env!("CARGO_BIN_EXE_volt"))
        .arg("--version")
        .output()
        .expect("volt çalışmalı");
    assert_eq!(out.status.code(), Some(0));
    assert_eq!(
        String::from_utf8_lossy(&out.stdout).trim(),
        format!("volt {}", expected())
    );
}

#[test]
fn sv_and_sdc_headers_carry_the_same_version_text() {
    let target = std::env::temp_dir().join(format!("volt-version-text-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&target);
    let out = Command::new(env!("CARGO_BIN_EXE_volt"))
        .args(["build", "--emit=sdc", "--target-dir"])
        .arg(&target)
        .arg(root().join("tests/fixtures/counter.volt"))
        .output()
        .expect("volt çalışmalı");
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let text = expected();
    let sv = std::fs::read_to_string(target.join("rtl/Counter.sv")).expect("SV");
    assert!(sv.contains(&format!("// Version: {text}\n")), "{sv}");
    let sdc = std::fs::read_to_string(target.join("constraints/Counter.sdc")).expect("SDC");
    assert!(
        sdc.starts_with(&format!("# Generated by Volt {text}\n")),
        "{sdc}"
    );
    let _ = std::fs::remove_dir_all(&target);
}
