#!/usr/bin/env python3
"""Turn an `objcopy -O verilog` byte dump into a Volt ROM module.

    python3 hex2volt.py hello.hex HelloRom > hello_rom.volt

The test language of `volt test` has no arrays, loops or file access, so
a program cannot be poked into memory from a test block. The ROM is a
generated Volt file instead: a `const` word table behind a two-port
(instruction + data) read-only module. riscv_core.volt and
hello_soc.volt never change when the program does — only this file.
"""

import sys

MIN_INDEX_BITS = 1
MAX_WORDS = 4096          # volt-sv-emit const table limit (ADR-0041)
WORDS_PER_LINE = 4


def read_bytes(path):
    """Parse `@ADDR` / `XX XX ...` lines into {byte address: value}."""
    image = {}
    addr = 0
    with open(path, encoding="ascii") as f:
        for token in f.read().split():
            if token.startswith("@"):
                addr = int(token[1:], 16)
            else:
                image[addr] = int(token, 16)
                addr += 1
    if not image:
        sys.exit(f"{path}: no data")
    return image


def to_words(image):
    """Little-endian 32-bit words from address 0, zero padded to 2^k."""
    used = (max(image) + 4) // 4
    index_bits = max(MIN_INDEX_BITS, (used - 1).bit_length())
    if (1 << index_bits) > MAX_WORDS:
        sys.exit(f"program needs {used} words, limit is {MAX_WORDS}")
    words = [
        sum(image.get(4 * w + b, 0) << (8 * b) for b in range(4))
        for w in range(1 << index_bits)
    ]
    return words, used, index_bits


def emit(words, used, index_bits, module, source):
    n = len(words)
    hi = index_bits + 1
    table = module.upper() + "_WORDS"
    rows = [
        "    " + ", ".join(f"0x{w:08X}" for w in words[i:i + WORDS_PER_LINE])
        for i in range(0, n, WORDS_PER_LINE)
    ]
    return f"""// GENERATED by hex2volt.py from {source} — do not edit; run `make`.
//
// {used} program words ({4 * used} bytes) zero-padded to {n}. A zero
// word is an illegal instruction, so running off the end traps.
// Addresses wrap inside the table (bits [{hi}:2] index it); `ifault` /
// `dfault` report an address that does not belong to it.

const {table} : [u32; {n}] = [
{(","+chr(10)).join(rows)}
]

pub module {module} {{
    in  iaddr  : u32     // instruction byte address (pc)
    in  daddr  : u32     // data byte address; the byte lane is the core's job
    out idata  : u32
    out ddata  : u32
    out ifault : bool    // pc misaligned or past the table
    out dfault : bool    // data address past the table

    idata  = {table}[iaddr[{hi}:2] as u{index_bits}]
    ddata  = {table}[daddr[{hi}:2] as u{index_bits}]
    ifault = (iaddr >> {hi + 1}) != 0 || (iaddr & 3) != 0
    dfault = (daddr >> {hi + 1}) != 0
}}
"""


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    path, module = sys.argv[1], sys.argv[2]
    words, used, index_bits = to_words(read_bytes(path))
    sys.stdout.write(emit(words, used, index_bits, module, path))


if __name__ == "__main__":
    main()
