[package]
name = "volt-syntax-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
volt-syntax = { path = "../crates/volt-syntax" }
volt-span = { path = "../crates/volt-span" }

[[bin]]
name = "parse_never_panics"
path = "fuzz_targets/parse_never_panics.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
