//~ E0009
// ADR-0076: @source belongs to an extern module; a Volt module's
// SystemVerilog is generated by the compiler.
@source("rtl/top.sv")
//~^ ERROR only to an 'extern module'
module Top {
    in  a : bool
    out y : bool
    y = a
}
