//! volt-sv-emit birim testleri.
//!
//! Kural referansları: docs/spec/sv-mapping.md.
//! KRİTİK: counter.volt çıktısı counter.expected.sv ile BİREBİR eşleşmeli.

use volt_span::FileId;
use volt_sv_emit::{emit, EmitResult};

fn compile(src: &str, name: &str) -> EmitResult {
    let parsed = volt_syntax::parser::parse(FileId(0), src);
    assert!(
        parsed.diagnostics.is_empty(),
        "parse hatasız olmalı: {:?}",
        parsed.error_codes()
    );
    emit(&parsed.ast, name)
}

fn sv(src: &str) -> String {
    let result = compile(src, "test.volt");
    assert!(
        !result.has_errors(),
        "emit hatasız olmalı: {:?}",
        result
            .diagnostics
            .iter()
            .map(|d| d.code.as_str())
            .collect::<Vec<_>>()
    );
    result.sv
}

fn emit_codes(src: &str) -> Vec<&'static str> {
    let parsed = volt_syntax::parser::parse(FileId(0), src);
    let result = emit(&parsed.ast, "test.volt");
    result.diagnostics.iter().map(|d| d.code.as_str()).collect()
}

/// sv-mapping.md §11 yasak yapı denetimi.
fn assert_no_forbidden(sv: &str) {
    for line in sv.lines() {
        let code = line.split("//").next().unwrap_or("");
        assert!(
            !code.contains("always ") && !code.trim_end().ends_with("always"),
            "çıplak 'always' yasak: {line}"
        );
        assert!(
            !code.contains("reg ") && !code.contains(" reg;"),
            "'reg' yasak (logic kullanılmalı): {line}"
        );
        assert!(!code.contains("initial"), "'initial' yasak: {line}");
        assert!(!code.contains('#'), "'#' gecikme yasak: {line}");
        assert!(
            !code.contains("casex") && !code.contains("casez"),
            "casex/casez yasak: {line}"
        );
    }
}

// ═══ KRİTİK: birebir snapshot ═════════════════════════════════════

#[test]
fn counter_matches_expected_sv_byte_for_byte() {
    let src = include_str!("../../../tests/fixtures/counter.volt");
    let expected = include_str!("../../../tests/fixtures/counter.expected.sv");
    let result = compile(src, "counter.volt");
    assert!(!result.has_errors());
    assert_eq!(
        result.sv, expected,
        "üretilen SV beklenen dosyayla birebir eşleşmeli"
    );
}

#[test]
fn counter_output_has_no_forbidden_constructs() {
    let src = include_str!("../../../tests/fixtures/counter.volt");
    assert_no_forbidden(&compile(src, "counter.volt").sv);
}

// ═══ Başlık ve altbilgi (§12) ═════════════════════════════════════

#[test]
fn header_contains_source_and_version() {
    let out = sv("module M { in a : u8 out b : u8 b = a }");
    assert!(out.starts_with("// This file was generated by Volt.\n"));
    assert!(out.contains("// Source:  test.volt\n"));
    assert!(out.contains("// Version: 0.1.0\n"));
    assert!(out.contains("`default_nettype none\n"));
}

#[test]
fn header_is_deterministic_no_date() {
    let out = sv("module M { in a : u8 out b : u8 b = a }");
    assert!(
        !out.contains("tarih"),
        "deterministik build'de tarih olmamalı"
    );
    assert!(!out.contains("Üretim"));
}

#[test]
fn footer_restores_default_nettype() {
    let out = sv("module M { in a : u8 out b : u8 b = a }");
    assert!(out.ends_with("`default_nettype wire\n"));
}

// ═══ Tip eşleme (§2) ══════════════════════════════════════════════

#[test]
fn type_map_unsigned_widths() {
    let out = sv("module M { in a : u8 in b : u16 in c : u32 in d : u64 out y : bool y = a[0] }");
    assert!(out.contains("input  logic [7:0]  a,"));
    assert!(out.contains("input  logic [15:0] b,"));
    assert!(out.contains("input  logic [31:0] c,"));
    assert!(out.contains("input  logic [63:0] d,"));
}

#[test]
fn type_map_bool_is_bare_logic() {
    let out = sv("module M { in f : bool out y : bool y = f }");
    assert!(out.contains("input  logic f,"), "çıktı:\n{out}");
}

#[test]
fn type_map_signed() {
    let out = sv("module M { in a : i8 in b : i16 out y : bool y = a[0] }");
    assert!(out.contains("input  logic signed [7:0]  a,"));
    assert!(out.contains("input  logic signed [15:0] b,"));
}

#[test]
fn type_map_bits_const_expr() {
    let out = sv("module M { in a : bits<4> in b : bits<4 + 4> out y : bool y = a[0] }");
    assert!(out.contains("input  logic [3:0] a,"));
    assert!(out.contains("input  logic [7:0] b,"));
}

// ═══ Port sırası (§1) ═════════════════════════════════════════════

#[test]
fn port_order_clock_reset_in_out() {
    // Kaynakta out önce yazılsa bile sıra: clock → rst → in → out
    let out = sv(
        "module M { out y : u8 in clk : clock in a : u8 reg r : u8 = 0 on clk { r <= a } y = r }",
    );
    let clk_pos = out.find(" clk,").unwrap();
    let rst_pos = out.find(" rst,").unwrap();
    let a_pos = out.find(" a,").unwrap();
    let y_pos = out.find(" y\n").unwrap();
    assert!(
        clk_pos < rst_pos && rst_pos < a_pos && a_pos < y_pos,
        "sıra bozuk:\n{out}"
    );
}

#[test]
fn no_clock_means_no_reset_port() {
    let out = sv("module M { in a : u8 out b : u8 b = a }");
    assert!(
        !out.contains("rst"),
        "saatsiz modülde reset olmamalı:\n{out}"
    );
}

// ═══ Reset varyantları (§7) ═══════════════════════════════════════

#[test]
fn reset_default_sync_active_high() {
    let out = sv("module M { in clk : clock reg r : u8 = 0 on clk { r <= r } }");
    assert!(out.contains("input  logic rst\n"), "çıktı:\n{out}");
    assert!(out.contains("always_ff @(posedge clk) begin"));
    assert!(out.contains("        if (rst) begin"));
}

#[test]
fn reset_sync_active_low() {
    let out = sv("domain D { clock = posedge, reset = sync active_low }\n\
         module M { in clk : clock @D reg r : u8 = 0 on clk { r <= r } }");
    assert!(out.contains("input  logic rst_n\n"), "çıktı:\n{out}");
    assert!(out.contains("always_ff @(posedge clk) begin"));
    assert!(out.contains("if (!rst_n) begin"));
}

#[test]
fn reset_async_active_high() {
    let out = sv("domain D { clock = posedge, reset = async active_high }\n\
         module M { in clk : clock @D reg r : u8 = 0 on clk { r <= r } }");
    assert!(out.contains("always_ff @(posedge clk or posedge rst) begin"));
    assert!(out.contains("if (rst) begin"));
}

#[test]
fn reset_async_active_low_negedge_clock() {
    // sv-mapping.md §4 asenkron varyant + negedge saat (ui/pass/19 deseni)
    let out = sv(
        "domain UsbDomain { clock = negedge, reset = async active_low }\n\
         module M { in usb_clk : clock @UsbDomain in data : u8 out q : u8 \
         reg buffer : u8 = 0 on usb_clk { buffer <= data } q = buffer }",
    );
    assert!(
        out.contains("always_ff @(negedge usb_clk or negedge rst_n) begin"),
        "çıktı:\n{out}"
    );
    assert!(out.contains("if (!rst_n) begin"));
    assert!(out.contains("buffer <= 8'd0;"));
}

#[test]
fn reset_none_no_port_no_reset_block() {
    let out = sv("domain Free { clock = posedge, reset = none }\n\
         module M { in clk : clock @Free reg r : u8 = 0 on clk { r <= r } }");
    assert!(!out.contains("rst"), "reset=none → port yok:\n{out}");
    assert!(!out.contains("if ("), "reset bloğu olmamalı:\n{out}");
    assert!(out.contains("always_ff @(posedge clk) begin\n        r <= r;\n    end"));
}

// ═══ reg ve on bloğu (§3, §4) ═════════════════════════════════════

#[test]
fn reg_becomes_logic_without_initializer() {
    let out = sv("module M { in clk : clock reg r : u16 = 0 on clk { r <= r } }");
    assert!(out.contains("\n    logic [15:0] r;\n"));
    assert!(
        !out.contains("logic [15:0] r = "),
        "başlangıç değeri bildirimde olmamalı"
    );
}

#[test]
fn reg_init_lands_in_reset_block_with_width() {
    let out = sv("module M { in clk : clock reg r : u16 = 0 on clk { r <= r } }");
    assert!(out.contains("            r <= 16'd0;"));
}

#[test]
fn reg_missing_type_is_e2012() {
    assert!(
        emit_codes("module M { in clk : clock reg r = 0 on clk { r <= r } }").contains(&"E2012")
    );
}

#[test]
fn multiple_regs_reset_in_declaration_order() {
    let out = sv(
        "module M { in clk : clock reg a : u8 = 1 reg b : bool = false \
         on clk { b <= a[0] a <= a } }",
    );
    let a_pos = out.find("a <= 8'd1;").expect("a reset");
    let b_pos = out.find("b <= 1'b0;").expect("b reset");
    assert!(a_pos < b_pos, "bildirim sırası korunmalı:\n{out}");
}

#[test]
fn else_if_chain_in_always_ff() {
    let out = sv(
        "module M { in clk : clock in clear : bool in enable : bool \
         reg acc : u16 = 0 on clk { if clear { acc <= 0 } else if enable { acc <= acc + 1 } } }",
    );
    assert!(out.contains("            if (clear) begin"));
    assert!(out.contains("            end else if (enable) begin"));
    assert!(out.contains("acc <= acc + 16'd1;"));
}

// ═══ Kombinasyonel (§5) ═══════════════════════════════════════════

#[test]
fn simple_connection_is_assign() {
    let out = sv("module M { in a : u8 out b : u8 b = a }");
    assert!(out.contains("\n    assign b = a;\n"));
}

#[test]
fn let_becomes_wire_with_width() {
    let out = sv("module M { in a : u8 in b : u8 out y : u8 let s = a + b y = s }");
    assert!(
        out.contains("\n    wire [7:0] s = a + b;\n"),
        "çıktı:\n{out}"
    );
}

#[test]
fn if_expr_becomes_ternary() {
    let out =
        sv("module M { in sel : bool in a : u8 in b : u8 out y : u8 y = if sel { a } else { b } }");
    assert!(out.contains("    assign y = sel ? a : b;"), "çıktı:\n{out}");
}

#[test]
fn nested_if_expr_parenthesized_ternary() {
    // §5.4: a ? 8'd1 : (b ? 8'd2 : 8'd3)
    let out = sv(
        "module M { in a : bool in b : bool out y : u8 y = if a { 1 } else if b { 2 } else { 3 } }",
    );
    assert!(
        out.contains("assign y = a ? 8'd1 : (b ? 8'd2 : 8'd3);"),
        "çıktı:\n{out}"
    );
}

// ═══ Operatörler ve dönüşümler (§6) ═══════════════════════════════

#[test]
fn cast_zero_extend() {
    let out = sv("module M { in a : u8 out y : u16 y = a as u16 }");
    assert!(out.contains("assign y = {{8{1'b0}}, a};"), "çıktı:\n{out}");
}

#[test]
fn cast_sign_extend() {
    let out = sv("module M { in a : i8 out y : bool let w = a as i16 y = w[0] }");
    assert!(out.contains("{{8{a[7]}}, a}"), "çıktı:\n{out}");
}

#[test]
fn bit_and_range_select() {
    let out = sv(
        "module M { in data : u8 out msb : bool out upper : bits<4> \
         msb = data[7] upper = data[7:4] }",
    );
    assert!(out.contains("assign msb = data[7];"));
    assert!(out.contains("assign upper = data[7:4];"));
}

#[test]
fn bitwise_and_unary_ops() {
    let out = sv("module M { in a : u8 in b : u8 out x : u8 out n : u8 x = a & b n = ~a }");
    assert!(out.contains("assign x = a & b;"));
    assert!(out.contains("assign n = ~a;"));
}

#[test]
fn precedence_parens_preserved_in_output() {
    let out = sv("module M { in a : u8 in b : u8 in c : u8 out y : u8 y = (a + b) * c }");
    assert!(out.contains("assign y = (a + b) * c;"), "çıktı:\n{out}");
}

// ═══ Literaller (§10) ═════════════════════════════════════════════

#[test]
fn literal_sizing_dec_hex_bin() {
    let out = sv(
        "module M { in a : u8 out x : u8 out h : u8 out b : bits<4> \
         x = a + 1 h = 0xFF b = 0b1010 }",
    );
    assert!(out.contains("a + 8'd1"), "dec: {out}");
    assert!(out.contains("assign h = 8'hFF;"), "hex: {out}");
    assert!(out.contains("assign b = 4'b1010;"), "bin: {out}");
}

#[test]
fn bool_literals() {
    let out = sv("module M { out t : bool out f : bool t = true f = false }");
    assert!(out.contains("assign t = 1'b1;"));
    assert!(out.contains("assign f = 1'b0;"));
}

#[test]
fn ambiguous_literal_is_e2005() {
    // let genişliği yalnız literalden çıkarılamaz → E2005, tahmin yok
    assert!(emit_codes("module M { let x = 0 }").contains(&"E2005"));
}

// ═══ Doc yorumları (İ5) ═══════════════════════════════════════════

#[test]
fn doc_comments_transferred_as_line_comments() {
    let out = sv("/// deneme modülü\n/// ikinci satır\nmodule M { in a : u8 out b : u8 b = a }");
    assert!(
        out.contains("// deneme modülü\n// ikinci satır\nmodule M ("),
        "çıktı:\n{out}"
    );
}

// ═══ Kapsam dışı (E0003) ══════════════════════════════════════════

#[test]
fn trit_port_is_e0003() {
    assert!(emit_codes("module M { in t : Trit out y : bool y = true }").contains(&"E0003"));
}

#[test]
fn call_expr_is_e0003() {
    // NOT: 'sync' aktif anahtar kelime olduğundan sync() çağrısı parser'da
    // E0001 verir; Call düğümü ancak sıradan bir isimle oluşur. sync()'in
    // CDC çağrısı olarak özel ele alınması F1 parser işi.
    assert!(emit_codes("module M { in a : u8 out y : u8 y = stretch(a) }").contains(&"E0003"));
}

// ═══ CDC köprüsü (§8) ═════════════════════════════════════════════

const BRIDGE_SRC: &str = "domain Fast { clock = posedge, reset = sync active_high }\n\
     domain Slow { clock = posedge, reset = sync active_high }\n\
     module CdcBridge { in fast_clk : clock @Fast in slow_clk : clock @Slow \
     in fast_flag : bool @Fast out slow_flag : bool @Slow \
     slow_flag = sync(fast_flag, slow_clk) }";

#[test]
fn sync_bridge_emits_without_errors() {
    let out = sv(BRIDGE_SRC);
    assert!(out.contains("module CdcBridge ("), "çıktı:\n{out}");
}

#[test]
fn sync_bridge_has_sdc_hint_comment() {
    let out = sv(BRIDGE_SRC);
    assert!(
        out.contains("// CDC synchronizer: fast_clk -> slow_clk"),
        "çıktı:\n{out}"
    );
}

#[test]
fn sync_bridge_two_always_ff_blocks() {
    // Kaynak alanda yakalama + hedef alanda iki aşama = iki always_ff
    let out = sv(BRIDGE_SRC);
    assert_eq!(out.matches("always_ff").count(), 2, "çıktı:\n{out}");
    assert!(out.contains("always_ff @(posedge fast_clk) begin"));
    assert!(out.contains("always_ff @(posedge slow_clk) begin"));
}

#[test]
fn sync_bridge_stage_naming_and_chain() {
    let out = sv(BRIDGE_SRC);
    assert!(out.contains("logic sync_fast_flag_src;"), "çıktı:\n{out}");
    assert!(out.contains("logic sync_fast_flag_stage0;"));
    assert!(out.contains("logic sync_fast_flag_stage1;"));
    assert!(out.contains("sync_fast_flag_src <= fast_flag;"));
    assert!(out.contains("sync_fast_flag_stage0 <= sync_fast_flag_src;"));
    assert!(out.contains("sync_fast_flag_stage1 <= sync_fast_flag_stage0;"));
    assert!(out.contains("assign slow_flag = sync_fast_flag_stage1;"));
}

#[test]
fn sync_bridge_resets_stages_to_zero() {
    let out = sv(BRIDGE_SRC);
    assert!(out.contains("sync_fast_flag_src <= 1'b0;"), "çıktı:\n{out}");
    assert!(out.contains("sync_fast_flag_stage0 <= 1'b0;"));
    assert!(out.contains("sync_fast_flag_stage1 <= 1'b0;"));
}

#[test]
fn sync_bridge_no_forbidden_constructs() {
    assert_no_forbidden(&sv(BRIDGE_SRC));
}

#[test]
fn sync3_bridge_three_dest_stages() {
    let src = "domain Fast { clock = posedge, reset = sync active_high }\n\
         domain Slow { clock = posedge, reset = sync active_high }\n\
         module M { in fast_clk : clock @Fast in slow_clk : clock @Slow \
         in f : bool @Fast out s : bool @Slow s = sync3(f, slow_clk) }";
    let out = sv(src);
    assert!(out.contains("logic sync_f_stage2;"), "çıktı:\n{out}");
    assert!(out.contains("sync_f_stage2 <= sync_f_stage1;"));
    assert!(out.contains("assign s = sync_f_stage2;"));
}

#[test]
fn sync_bridge_multi_bit_width() {
    let src = "domain Fast { clock = posedge, reset = sync active_high }\n\
         domain Slow { clock = posedge, reset = sync active_high }\n\
         module M { in fast_clk : clock @Fast in slow_clk : clock @Slow \
         in d : u8 @Fast out q : u8 @Slow q = sync(d, slow_clk) }";
    let out = sv(src);
    assert!(out.contains("logic [7:0] sync_d_stage0;"), "çıktı:\n{out}");
    assert!(out.contains("sync_d_stage0 <= 8'd0;"));
}

#[test]
fn sync_bridge_dest_reset_none() {
    let src = "domain Fast { clock = posedge, reset = sync active_high }\n\
         domain Free { clock = posedge, reset = none }\n\
         module M { in fast_clk : clock @Fast in free_clk : clock @Free \
         in f : bool @Fast out s : bool @Free s = sync(f, free_clk) }";
    let out = sv(src);
    // Hedef alanda reset yok → hedef bloğunda if yok, aşamalar doğrudan
    assert!(
        out.contains(
            "    always_ff @(posedge free_clk) begin\n        \
             sync_f_stage0 <= sync_f_src;\n        \
             sync_f_stage1 <= sync_f_stage0;\n    end"
        ),
        "çıktı:\n{out}"
    );
}

#[test]
fn sync_unknown_clock_is_error() {
    let src = "module M { in clk : clock in f : bool out s : bool s = sync(f, nope) }";
    assert!(emit_codes(src).contains(&"E0003"));
}

// ═══ Çoklu saat alanı (§7 genişletmesi) ═══════════════════════════

#[test]
fn multi_domain_shared_reset_port_emitted_once() {
    // İki alan da sync active_high → tek 'rst' portu
    let out = sv(BRIDGE_SRC);
    assert_eq!(out.matches("input  logic rst").count(), 1, "çıktı:\n{out}");
}

#[test]
fn multi_domain_distinct_reset_ports_in_clock_order() {
    let src = "domain Fast { clock = posedge, reset = sync active_high }\n\
         domain Usb { clock = negedge, reset = async active_low }\n\
         module M { in fclk : clock @Fast in uclk : clock @Usb \
         in a : bool @Fast in b : u8 @Usb out x : bool @Fast out y : u8 @Usb \
         reg ra : bool = false reg rb : u8 = 0 \
         on fclk { ra <= a } on uclk { rb <= b } x = ra y = rb }";
    let out = sv(src);
    let fclk = out.find(" fclk,").unwrap();
    let uclk = out.find(" uclk,").unwrap();
    let rst = out.find(" rst,").unwrap();
    let rst_n = out.find(" rst_n,").unwrap();
    let a = out.find(" a,").unwrap();
    assert!(
        fclk < uclk && uclk < rst && rst < rst_n && rst_n < a,
        "sıra: clock'lar → reset'ler → in:\n{out}"
    );
}

#[test]
fn on_block_uses_its_own_clock_domain() {
    let src = "domain Fast { clock = posedge, reset = sync active_high }\n\
         domain Usb { clock = negedge, reset = async active_low }\n\
         module M { in fclk : clock @Fast in uclk : clock @Usb \
         in a : bool @Fast in b : u8 @Usb out x : bool @Fast out y : u8 @Usb \
         reg ra : bool = false reg rb : u8 = 0 \
         on fclk { ra <= a } on uclk { rb <= b } x = ra y = rb }";
    let out = sv(src);
    assert!(
        out.contains("always_ff @(posedge fclk) begin"),
        "çıktı:\n{out}"
    );
    assert!(out.contains("        if (rst) begin"));
    assert!(out.contains("always_ff @(negedge uclk or negedge rst_n) begin"));
    assert!(out.contains("        if (!rst_n) begin"));
}

// ═══ ui/pass taraması ═════════════════════════════════════════════

#[test]
fn ui_pass_sweep_no_panics_and_f0_files_emit_clean_sv() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/ui/pass");
    // F0 kapsamında temiz SV üretmesi ZORUNLU dosyalar
    let must_emit = [
        "01_minimal_module.volt",
        "03_conditional.volt",
        "04_operator_precedence.volt",
        "05_multi_stmt_sequential.volt",
        "06_let_binding.volt",
        "09_bitwise_no_widening.volt",
        "11_bit_and_range_select.volt",
        "13_cdc_correct_bridge.volt",
        "14_single_clock_no_domain.volt",
        "15_nested_conditionals.volt",
        // F5 (ADR-0027): yerleşik CDC primitifleri temiz SV üretmeli.
        "27_async_fifo.volt",
        "28_handshake_sync.volt",
        "29_pulse_sync.volt",
        // F5 (ADR-0029): tek saatli stdlib yapı taşları.
        "30_sync_fifo.volt",
        "31_ram.volt",
        "32_counter.volt",
        "33_shift_register.volt",
        "34_arbiter.volt",
        "35_edge_detect.volt",
    ];

    let mut clean = 0;
    let mut skipped = 0;
    for entry in std::fs::read_dir(dir).expect("ui/pass okunmalı") {
        let path = entry.expect("girdi").path();
        if path.extension().and_then(|e| e.to_str()) != Some("volt") {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let src = std::fs::read_to_string(&path).expect("dosya okunmalı");

        // Panik yok garantisi: parse + emit her dosyada çalışır
        let parsed = volt_syntax::parser::parse(FileId(0), &src);
        let result = emit(&parsed.ast, &name);

        let all_clean = parsed.diagnostics.is_empty() && !result.has_errors();
        if all_clean {
            assert!(result.sv.contains("module"), "{name}: SV üretilmeli");
            assert_no_forbidden(&result.sv);
            clean += 1;
        } else {
            skipped += 1;
        }
        if must_emit.contains(&name.as_str()) {
            assert!(
                all_clean,
                "{name} F0 kapsamında, temiz SV üretmeli; parse: {:?}, emit: {:?}",
                parsed.error_codes(),
                result
                    .diagnostics
                    .iter()
                    .map(|d| d.code.as_str())
                    .collect::<Vec<_>>()
            );
        }
    }
    assert!(
        clean >= must_emit.len(),
        "temiz: {clean}, atlanan: {skipped}"
    );
}

#[test]
fn multiple_modules_in_one_file() {
    let out =
        sv("module A { in a : u8 out b : u8 b = a }\nmodule B { in x : bool out y : bool y = x }");
    assert!(out.contains("module A ("));
    assert!(out.contains("module B ("));
    let a_end = out.find("endmodule").unwrap();
    assert!(
        out[a_end..].contains("module B ("),
        "modüller sıralı olmalı"
    );
}

// ═══ Yerleşik CDC primitifleri (ADR-0027) ═════════════════════

const CDC_DOMAINS: &str = "domain Fast { clock = posedge, reset = sync active_high }
                           domain Slow { clock = posedge, reset = sync active_high }
";

fn fifo_src(depth: &str) -> String {
    format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in din : u8 @Fast in push : bool @Fast in pop : bool @Slow          out dout : u8 @Slow out full : bool @Fast out empty : bool @Slow          let f = AsyncFifo<u8, {depth}> {{ wr_clk: fast_clk, wr_data: din, wr_en: push,          rd_clk: slow_clk, rd_en: pop }}          full = f.wr_full dout = f.rd_data empty = f.rd_empty }}"
    )
}

fn hs_src() -> String {
    format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in din : u8 @Fast in s : bool @Fast          out busy : bool @Fast out dout : u8 @Slow out valid : bool @Slow          let h = HandshakeSync<u8> {{ src_clk: fast_clk, data_in: din, send: s,          dst_clk: slow_clk }}          busy = h.busy dout = h.data_out valid = h.valid }}"
    )
}

fn ps_src() -> String {
    format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in p : bool @Fast out q : bool @Slow          let u = PulseSync {{ src_clk: fast_clk, pulse_in: p, dst_clk: slow_clk }}          q = u.pulse_out }}"
    )
}

fn emit_immediate(src: &str) -> volt_sv_emit::EmitOutput {
    let parsed = volt_syntax::parser::parse(FileId(0), src);
    assert!(
        parsed.diagnostics.is_empty(),
        "parse hatasız olmalı: {:?}",
        parsed.error_codes()
    );
    volt_sv_emit::emit_full(
        &parsed.ast,
        "test.volt",
        src,
        volt_sv_emit::SvaMode::Immediate,
    )
}

#[test]
fn async_fifo_emits_mem_and_gray_pointers() {
    let out = sv(&fifo_src("16"));
    assert!(out.contains("f_mem ["), "bellek dizisi: {out}");
    assert!(out.contains("f_wgray"), "yazma gray pointer'ı: {out}");
    assert!(out.contains("f_rgray_s1"), "iki-flop senkron: {out}");
    assert!(out.contains("localparam int f_DEPTH = 16;"), "{out}");
    assert!(
        out.contains("assign f_rd_empty = (f_rgray == f_wgray_s1);"),
        "{out}"
    );
    assert_no_forbidden(&out);
}

#[test]
fn async_fifo_field_access_becomes_prefixed_signal() {
    let out = sv(&fifo_src("16"));
    assert!(out.contains("assign dout = f_rd_data;"), "{out}");
    assert!(out.contains("assign full = f_wr_full;"), "{out}");
    assert!(!out.contains("f.rd_data"), "alan erişimi çevrilmeli: {out}");
}

#[test]
fn async_fifo_depth_12_is_e2025() {
    let codes = emit_codes(&fifo_src("12"));
    assert!(codes.contains(&"E2025"), "E2025 bekleniyor: {codes:?}");
}

#[test]
fn async_fifo_depth_2_special_cases_full_flag() {
    // AW==1: sıfır genişlikli dilim yerine pointer'ın tamamı terslenir.
    let out = sv(&fifo_src("2"));
    assert!(
        out.contains("assign f_wr_full = (f_wgray == ~f_rgray_s1);"),
        "{out}"
    );
}

#[test]
fn handshake_sync_emits_req_ack_and_data_reg() {
    let out = sv(&hs_src());
    assert!(out.contains("h_req_s1"), "req senkronu: {out}");
    assert!(out.contains("h_ack_s1"), "ack senkronu: {out}");
    assert!(out.contains("h_data_q"), "veri register'ı: {out}");
    assert!(out.contains("assign h_busy = h_req || h_ack_s1;"), "{out}");
    assert!(out.contains("assign dout = h_data_out;"), "{out}");
    assert_no_forbidden(&out);
}

#[test]
fn pulse_sync_emits_toggle_and_edge_detect() {
    let out = sv(&ps_src());
    assert!(out.contains("u_toggle <= ~u_toggle;"), "{out}");
    assert!(
        out.contains("assign u_pulse_out = u_sync1 ^ u_sync2;"),
        "{out}"
    );
    assert_no_forbidden(&out);
}

#[test]
fn builtin_missing_binding_is_diagnosed() {
    let src = format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in p : bool @Fast out q : bool @Slow          let u = PulseSync {{ src_clk: fast_clk, dst_clk: slow_clk }}          q = u.pulse_out }}"
    );
    let codes = emit_codes(&src);
    assert!(codes.contains(&"E0003"), "eksik bağlama tanısı: {codes:?}");
}

#[test]
fn builtin_clock_binding_must_be_module_clock_port() {
    let src = format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in p : bool @Fast out q : bool @Slow          let u = PulseSync {{ src_clk: p, pulse_in: p, dst_clk: slow_clk }}          q = u.pulse_out }}"
    );
    let codes = emit_codes(&src);
    assert!(codes.contains(&"E0003"), "saat bağlama tanısı: {codes:?}");
}

#[test]
fn immediate_mode_adds_volt_markers_and_props() {
    let out = emit_immediate(&fifo_src("16"));
    assert!(
        out.diagnostics.is_empty(),
        "{:?}",
        out.diagnostics
            .iter()
            .map(|d| d.code.as_str())
            .collect::<Vec<_>>()
    );
    assert!(out.sv.contains("// volt:f_inv_0"), "{}", out.sv);
    assert!(out.sv.contains("// volt:f_cov_0"), "{}", out.sv);
    assert!(out.sv.contains("// volt:f_cov_1"), "{}", out.sv);
    assert!(out.sv.contains("initial assume (rst);"), "{}", out.sv);
    let names: Vec<&str> = out.sva_props.iter().map(|p| p.name.as_str()).collect();
    assert_eq!(names, ["f_inv_0", "f_cov_0", "f_cov_1"]);
    assert!(out.sva_props.iter().all(|p| p.module_name == "M"));
}

#[test]
fn immediate_mode_observers_are_formal_only() {
    // Immediate: gölge register'lar var; None modunda YOK (lint temiz).
    let imm = emit_immediate(&hs_src());
    assert!(imm.sv.contains("h_data_prev"), "{}", imm.sv);
    assert!(imm.sv.contains("// volt:h_inv_0"), "{}", imm.sv);
    let plain = sv(&hs_src());
    assert!(!plain.contains("h_data_prev"), "{plain}");
    assert!(!plain.contains("initial"), "{plain}");

    let imm = emit_immediate(&ps_src());
    assert!(imm.sv.contains("u_toggle_d"), "{}", imm.sv);
    assert!(imm.sv.contains("u_pin_d"), "{}", imm.sv);
    // Zayıflatılmış kontrat: toggle bütünlüğü (ADR-0027).
    assert!(
        imm.sv.contains("(u_toggle == u_toggle_d) || u_pin_d"),
        "{}",
        imm.sv
    );
    assert!(imm.sv.contains("// volt:u_inv_0"), "{}", imm.sv);
    assert!(imm.sv.contains("// volt:u_cov_0"), "{}", imm.sv);
    let plain = sv(&ps_src());
    assert!(!plain.contains("u_toggle_d"), "{plain}");
}

#[test]
fn immediate_mode_emits_formal_init_state() {
    // BMC reset durumundan başlar: clk2fflogic altında kenar örneklemeyen
    // alan hiç sıfırlanmaz — init bloğu tüm iç durumu reset değerine çeker.
    let imm = emit_immediate(&fifo_src("16"));
    assert!(imm.sv.contains("initial begin"), "{}", imm.sv);
    for reg in ["wbin", "wgray", "rbin", "rgray", "rgray_s1", "wgray_s1"] {
        assert!(imm.sv.contains(&format!("f_{reg} = 5'd0;")), "{}", imm.sv);
    }
    assert!(imm.sv.contains("f_rd_data = 8'd0;"), "{}", imm.sv);
    // İz ortası kısmi reset yasağı: her alanda kenar bazlı assume.
    assert!(
        imm.sv
            .contains("always @(posedge fast_clk) assume (!(rst)); // formal: no mid-trace reset"),
        "{}",
        imm.sv
    );
    assert!(
        imm.sv
            .contains("always @(posedge slow_clk) assume (!(rst));"),
        "{}",
        imm.sv
    );
    // Normal build çıktısı formal kurulumların hiçbirini görmez.
    let plain = sv(&fifo_src("16"));
    assert!(!plain.contains("initial begin"), "{plain}");
    assert!(!plain.contains("assume"), "{plain}");
}

#[test]
fn multiclock_modules_lists_two_clock_module_only() {
    let out = emit_immediate(&fifo_src("16"));
    assert_eq!(out.multiclock_modules, ["M"]);

    let single = "module S { in clk : clock in a : u8 out b : u8                   reg r : u8 = 0 on clk { r <= a } b = r }";
    let parsed = volt_syntax::parser::parse(FileId(0), single);
    let out = volt_sv_emit::emit_full(&parsed.ast, "t.volt", single, volt_sv_emit::SvaMode::None);
    assert!(out.multiclock_modules.is_empty());
}

#[test]
fn builtin_let_binding_of_output_gets_width() {
    // `let x = f.rd_data` — genişlik port tablosundan gelmeli (E2005 yok).
    let src = format!(
        "{CDC_DOMAINS}module M {{ in fast_clk : clock @Fast in slow_clk : clock @Slow          in din : u8 @Fast in push : bool @Fast in pop : bool @Slow          out dout : u8 @Slow          let f = AsyncFifo<u8, 16> {{ wr_clk: fast_clk, wr_data: din, wr_en: push,          rd_clk: slow_clk, rd_en: pop }}          let x = f.rd_data dout = x }}"
    );
    let out = sv(&src);
    assert!(out.contains("wire [7:0] x = f_rd_data;"), "{out}");
}
