//! ADR-0024: modül başına SV dosyası; ADR-0042: birim kaynakları.

use volt_span::FileId;
use volt_sv_emit::{emit_full, emit_unit, ConstArrayStyle, SourceText, SvaMode};
use volt_syntax::{parse, parse_unit};

const TWO: &str = "module A { in clk : clock in x : bool out y : bool y = x }\nmodule B { in clk : clock in x : bool out y : bool y = !x }\n";

#[test]
fn emit_full_returns_one_sv_per_module_with_module_header() {
    let parsed = parse(FileId(0), TWO);
    let out = emit_full(&parsed.ast, "two.volt", TWO, SvaMode::None);
    assert!(out.diagnostics.is_empty(), "{:?}", out.diagnostics);
    let names: Vec<&str> = out.modules.iter().map(|m| m.name.as_str()).collect();
    assert_eq!(names, ["A", "B"]);
    for m in &out.modules {
        assert!(
            m.sv.starts_with("// This file was generated by Volt."),
            "{}",
            m.sv
        );
        assert!(
            m.sv.contains(&format!("// Module:  {}\n", m.name)),
            "{}",
            m.sv
        );
        assert!(m.sv.contains(&format!("module {} (", m.name)), "{}", m.sv);
        assert!(m.sv.contains("`default_nettype none"));
        assert!(
            m.sv.trim_end().ends_with("`default_nettype wire"),
            "{}",
            m.sv
        );
    }
    // Birleşik çıktı değişmedi: başlıkta Module satırı yok, iki modül var.
    assert!(!out.sv.contains("// Module:"));
    assert!(out.sv.contains("module A (") && out.sv.contains("module B ("));
}

#[test]
fn per_module_header_names_the_module_source_file() {
    let a = "package lib;\npub module A { in clk : clock in x : bool out y : bool y = x }\n";
    let b = "use lib::A;\nmodule B { in clk : clock in x : bool out y : bool y = !x }\n";
    let parsed = parse_unit(&[(FileId(0), a), (FileId(1), b)]);
    let sources = [
        SourceText {
            file: FileId(1),
            name: "main.volt",
            text: b,
        },
        SourceText {
            file: FileId(0),
            name: "lib.volt",
            text: a,
        },
    ];
    let out = emit_unit(
        &parsed.ast,
        "main.volt",
        &sources,
        SvaMode::None,
        ConstArrayStyle::default(),
    );
    assert!(out.diagnostics.is_empty(), "{:?}", out.diagnostics);
    assert!(
        out.modules[0].sv.contains("// Source:  lib.volt"),
        "{}",
        out.modules[0].sv
    );
    assert!(
        out.modules[1].sv.contains("// Source:  main.volt"),
        "{}",
        out.modules[1].sv
    );
    assert!(out.sv.contains("// Source:  main.volt"));
}

#[test]
fn sva_comment_lines_are_numbered_per_source_file() {
    let a = "package lib;\n\n\npub module A {\n    in clk : clock\n    in x : bool\n    out y : bool\n    invariant: y == x\n    y = x\n}\n";
    let b = "use lib::A;\nmodule B {\n    in clk : clock\n    in x : bool\n    out y : bool\n    invariant: y != x\n    y = !x\n}\n";
    let parsed = parse_unit(&[(FileId(0), a), (FileId(1), b)]);
    let sources = [
        SourceText {
            file: FileId(1),
            name: "main.volt",
            text: b,
        },
        SourceText {
            file: FileId(0),
            name: "lib.volt",
            text: a,
        },
    ];
    let out = emit_unit(
        &parsed.ast,
        "main.volt",
        &sources,
        SvaMode::Inline,
        ConstArrayStyle::default(),
    );
    assert!(out.diagnostics.is_empty(), "{:?}", out.diagnostics);
    assert!(out.sv.contains("from lib.volt:8"), "{}", out.sv);
    assert!(out.sv.contains("from main.volt:6"), "{}", out.sv);
}
