//! Verilator C++ testbench üretimi (ADR-0033).
//!
//! İki üreteç var: `run_testbench_cpp` (`volt run` — duman koşusu,
//! çevrim tablosu) ve `test_testbench_cpp` (`volt test` — test bloğu
//! betiğini yürütür, makine-okur `VOLT-*` satırları basar; sürücü bu
//! satırları cargo biçimli rapora çevirir). Üretilen kod İngilizcedir
//! (ADR-0026).

use volt_ast::{ItemKind, ModuleDecl, PortDir, SourceFile, TypeRefKind};

/// Testbench'in bilmesi gereken port özeti.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimPort {
    pub name: String,
    pub is_input: bool,
    pub is_clock: bool,
}

/// Modülün portlarını testbench özetine indirger. Üretilen SV'deki
/// örtük `rst` girişi listeye DAHİL DEĞİLDİR — reset'i üreteçler
/// kendisi sürer.
pub fn collect_sim_ports(src: &SourceFile, module: &ModuleDecl) -> Vec<SimPort> {
    module
        .ports
        .iter()
        .map(|p| SimPort {
            name: p.name.text.clone(),
            is_input: p.direction == PortDir::In,
            is_clock: matches!(src.types[p.ty].kind, TypeRefKind::Clock),
        })
        .collect()
}

/// `sources` içinde adı verilen modülü bulur.
pub fn find_module<'a>(
    sources: &[&'a SourceFile],
    name: &str,
) -> Option<(&'a SourceFile, &'a ModuleDecl)> {
    for src in sources {
        for idx in &src.items {
            if let ItemKind::Module(m) = &src.items_arena[*idx].kind {
                if m.name.text == name {
                    return Some((*src, m));
                }
            }
        }
    }
    None
}

/// Bir test betiğinin tek adımı — sürücü, AST `TestStmt`'lerini satır
/// numaralarını çözerek bu biçime indirger.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TbStep {
    /// `dut.port = v;`
    SetPort { port: String, value: TbValue },
    /// `step(n);`
    Step(u64),
    /// `reset();`
    Reset,
    /// `assert_*(...)` — `loc` insan-okur konumdur (`dosya.volt:24`).
    Assert {
        kind: TbAssertKind,
        left: TbValue,
        right: TbValue,
        loc: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TbAssertKind {
    Eq,
    Ne,
    True,
    False,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TbValue {
    Lit(u64),
    /// `dut.port` okuması.
    Port(String),
}

/// Tek testin adı (görünen ad, boşluksuz) ve adımları.
#[derive(Debug, Clone)]
pub struct TbTest {
    pub name: String,
    pub steps: Vec<TbStep>,
}

/// Saat portlarını bir tam çevrim sürer: posedge + eval, negedge + eval.
/// (`eval()` Verilator modelinin devre değerlendirme API'sidir — kod
/// yürütme değildir.)
fn cycle_fn(ports: &[SimPort], trace: bool) -> String {
    let mut set_high = String::new();
    let mut set_low = String::new();
    for p in ports.iter().filter(|p| p.is_clock) {
        set_high.push_str(&format!("    dut->{} = 1;\n", p.name));
        set_low.push_str(&format!("    dut->{} = 0;\n", p.name));
    }
    let dump = if trace {
        "    ctx->timeInc(1);\n    tfp->dump(ctx->time());\n"
    } else {
        "    ctx->timeInc(1);\n"
    };
    let tfp_param = if trace { ", VerilatedVcdC* tfp" } else { "" };
    format!(
        "static void run_cycle(TOP* dut, VerilatedContext* ctx{tfp_param}) {{\n\
         {set_high}    dut->eval();\n{dump}\
         {set_low}    dut->eval();\n{dump}}}\n"
    )
}

/// 2 çevrimlik reset yardımcısı.
fn reset_fn(trace: bool) -> String {
    let (param, arg) = if trace {
        (", VerilatedVcdC* tfp", ", tfp")
    } else {
        ("", "")
    };
    format!(
        "static void apply_reset(TOP* dut, VerilatedContext* ctx{param}) {{\n\
         \x20   dut->rst = 1;\n\
         \x20   run_cycle(dut, ctx{arg});\n\
         \x20   run_cycle(dut, ctx{arg});\n\
         \x20   dut->rst = 0;\n\
         }}\n"
    )
}

fn header(module: &str, trace: bool) -> String {
    let mut out = String::new();
    out.push_str("// This file was generated by Volt. DO NOT EDIT.\n");
    out.push_str(&format!("#include \"V{module}.h\"\n"));
    out.push_str("#include \"verilated.h\"\n");
    if trace {
        out.push_str("#include \"verilated_vcd_c.h\"\n");
    }
    out.push_str("#include <cstdio>\n\n");
    out.push_str(&format!("using TOP = V{module};\n\n"));
    out
}

/// `volt run` testbench'i: 2 çevrim reset, `cycle 0` satırı, ardından
/// saat dışı girişler 1'e sürülür ve her çevrimde saat dışı tüm portlar
/// tablo satırı olarak basılır (cli-contract.md §7).
pub fn run_testbench_cpp(
    module: &str,
    ports: &[SimPort],
    cycles: u64,
    vcd_file: Option<&str>,
) -> String {
    let trace = vcd_file.is_some();
    let cols: Vec<&SimPort> = ports.iter().filter(|p| !p.is_clock).collect();

    let mut out = header(module, trace);
    out.push_str(&cycle_fn(ports, trace));
    out.push('\n');
    out.push_str(&reset_fn(trace));
    out.push('\n');

    // Sütun genişlikleri üretim anında sabitlenir (deterministik çıktı).
    let widths: Vec<usize> = cols.iter().map(|p| p.name.len().max(5)).collect();
    let mut head = format!("{:>5}", "cycle");
    let mut dashes = "-----".to_string();
    for (p, w) in cols.iter().zip(&widths) {
        head.push_str(&format!("  {:>w$}", p.name, w = w));
        dashes.push_str(&format!("  {}", "-".repeat(*w)));
    }

    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("    VerilatedContext ctx;\n");
    out.push_str("    ctx.commandArgs(argc, argv);\n");
    out.push_str("    TOP dut(&ctx);\n");
    if let Some(vcd) = vcd_file {
        out.push_str("    Verilated::traceEverOn(true);\n");
        out.push_str("    VerilatedVcdC vcd;\n");
        out.push_str("    dut.trace(&vcd, 99);\n");
        out.push_str(&format!("    vcd.open(\"{vcd}\");\n"));
    }
    let tfp_arg = if trace { ", &vcd" } else { "" };
    // Girişler resetten önce sıfırlanır (belirsiz başlangıç yok).
    for p in cols.iter().filter(|p| p.is_input) {
        out.push_str(&format!("    dut.{} = 0;\n", p.name));
    }
    out.push_str(&format!("    apply_reset(&dut, &ctx{tfp_arg});\n\n"));
    out.push_str(&format!("    std::printf(\"{head}\\n\");\n"));
    out.push_str(&format!("    std::printf(\"{dashes}\\n\");\n"));

    // Satır basıcı: cycle + saat dışı portlar.
    let mut fmt = "%5llu".to_string();
    let mut args = String::new();
    for (p, w) in cols.iter().zip(&widths) {
        fmt.push_str(&format!("  %{w}llu"));
        args.push_str(&format!(", (unsigned long long)dut.{}", p.name));
    }
    out.push_str(&format!(
        "    std::printf(\"{fmt}\\n\", (unsigned long long)0{args});\n\n"
    ));
    // Duman stimulusu: saat dışı girişler 1 (ADR-0033 — gerçek
    // doğrulama volt test'indir).
    for p in cols.iter().filter(|p| p.is_input) {
        out.push_str(&format!("    dut.{} = 1;\n", p.name));
    }
    out.push_str(&format!(
        "    for (unsigned long long c = 1; c <= {cycles}ULL; ++c) {{\n"
    ));
    out.push_str(&format!("        run_cycle(&dut, &ctx{tfp_arg});\n"));
    out.push_str(&format!("        std::printf(\"{fmt}\\n\", c{args});\n"));
    out.push_str("    }\n");
    if trace {
        out.push_str("    vcd.close();\n");
    }
    out.push_str("    dut.final();\n");
    out.push_str("    return 0;\n");
    out.push_str("}\n");
    out
}

/// TbValue → C++ ifadesi.
fn cpp_value(v: &TbValue) -> String {
    match v {
        TbValue::Lit(n) => format!("{n}ULL"),
        TbValue::Port(p) => format!("(unsigned long long)dut.{p}"),
    }
}

/// `volt test` testbench'i: her test taze DUT örneğiyle koşar, sonuç
/// `VOLT-TEST-BEGIN/END` ve ilk hata `VOLT-ASSERT-FAIL` satırlarıyla
/// stdout'a yazılır. Çıkış kodu: kalan test sayısı 0 ise 0, değilse 1.
pub fn test_testbench_cpp(module: &str, ports: &[SimPort], tests: &[TbTest]) -> String {
    let mut out = header(module, false);
    out.push_str(&cycle_fn(ports, false));
    out.push('\n');
    out.push_str(&reset_fn(false));
    out.push('\n');

    for (i, test) in tests.iter().enumerate() {
        // Her test KENDİ VerilatedContext'ini kurar: Verilator, zamanı
        // ilerlemiş bir context'e ikinci model eklenmesine izin vermez.
        out.push_str(&format!("static bool test_{i}() {{\n"));
        out.push_str("    VerilatedContext uctx;\n");
        out.push_str("    VerilatedContext* ctx = &uctx;\n");
        out.push_str("    TOP dut(ctx);\n");
        for p in ports.iter().filter(|p| p.is_input && !p.is_clock) {
            out.push_str(&format!("    dut.{} = 0;\n", p.name));
        }
        out.push_str("    apply_reset(&dut, ctx);\n");
        for step in &test.steps {
            match step {
                TbStep::SetPort { port, value } => {
                    out.push_str(&format!("    dut.{port} = {};\n", cpp_value(value)));
                }
                TbStep::Step(n) => {
                    out.push_str(&format!(
                        "    for (unsigned long long s = 0; s < {n}ULL; ++s) run_cycle(&dut, ctx);\n"
                    ));
                }
                TbStep::Reset => out.push_str("    apply_reset(&dut, ctx);\n"),
                TbStep::Assert {
                    kind,
                    left,
                    right,
                    loc,
                } => {
                    let l = cpp_value(left);
                    let r = cpp_value(right);
                    let (cond, name) = match kind {
                        TbAssertKind::Eq => (format!("({l}) == ({r})"), "assert_eq"),
                        TbAssertKind::Ne => (format!("({l}) != ({r})"), "assert_ne"),
                        TbAssertKind::True => (format!("({l}) != 0"), "assert_true"),
                        TbAssertKind::False => (format!("({l}) == 0"), "assert_false"),
                    };
                    out.push_str(&format!("    if (!({cond})) {{\n"));
                    out.push_str(&format!(
                        "        std::printf(\"VOLT-ASSERT-FAIL {name} {loc} left=%llu right=%llu\\n\", {l}, {r});\n"
                    ));
                    out.push_str("        dut.final();\n");
                    out.push_str("        return false;\n");
                    out.push_str("    }\n");
                }
            }
        }
        out.push_str("    dut.final();\n");
        out.push_str("    return true;\n");
        out.push_str("}\n\n");
    }

    out.push_str("int main(int, char**) {\n");
    out.push_str("    int failed = 0;\n");
    for (i, test) in tests.iter().enumerate() {
        out.push_str(&format!(
            "    std::printf(\"VOLT-TEST-BEGIN {}\\n\");\n",
            test.name
        ));
        out.push_str(&format!(
            "    if (test_{i}()) std::printf(\"VOLT-TEST-END {} ok\\n\");\n",
            test.name
        ));
        out.push_str(&format!(
            "    else {{ ++failed; std::printf(\"VOLT-TEST-END {} fail\\n\"); }}\n",
            test.name
        ));
    }
    out.push_str("    return failed == 0 ? 0 : 1;\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn counter_ports() -> Vec<SimPort> {
        vec![
            SimPort {
                name: "clk".into(),
                is_input: true,
                is_clock: true,
            },
            SimPort {
                name: "enable".into(),
                is_input: true,
                is_clock: false,
            },
            SimPort {
                name: "count".into(),
                is_input: false,
                is_clock: false,
            },
        ]
    }

    #[test]
    fn run_tb_has_table_header_and_smoke_stimulus() {
        let cpp = run_testbench_cpp("Counter", &counter_ports(), 10, None);
        assert!(cpp.contains("#include \"VCounter.h\""));
        assert!(cpp.contains("cycle  enable  count"));
        assert!(cpp.contains("-----  ------  -----"));
        // Reset öncesi girişler 0, duman stimulusu 1.
        assert!(cpp.contains("dut.enable = 0;"));
        assert!(cpp.contains("dut.enable = 1;"));
        assert!(cpp.contains("c <= 10ULL"));
        // VCD kapalıyken trace başlığı yok.
        assert!(!cpp.contains("verilated_vcd_c.h"));
    }

    #[test]
    fn run_tb_vcd_enables_trace() {
        let cpp = run_testbench_cpp("Counter", &counter_ports(), 5, Some("waves.vcd"));
        assert!(cpp.contains("verilated_vcd_c.h"));
        assert!(cpp.contains("vcd.open(\"waves.vcd\")"));
        assert!(cpp.contains("vcd.close()"));
        assert!(cpp.contains("tfp->dump(ctx->time())"));
    }

    #[test]
    fn run_tb_toggles_clock_and_resets_two_cycles() {
        let cpp = run_testbench_cpp("Counter", &counter_ports(), 1, None);
        assert!(cpp.contains("dut->clk = 1;"));
        assert!(cpp.contains("dut->clk = 0;"));
        assert!(cpp.contains("dut->rst = 1;"));
        // apply_reset gövdesinde iki run_cycle çağrısı.
        let reset_body = cpp
            .split("apply_reset")
            .nth(1)
            .expect("apply_reset gövdesi");
        assert_eq!(reset_body.matches("run_cycle").count(), 2);
    }

    #[test]
    fn test_tb_emits_protocol_lines_and_asserts() {
        let tests = vec![TbTest {
            name: "start_bit_is_low".into(),
            steps: vec![
                TbStep::SetPort {
                    port: "enable".into(),
                    value: TbValue::Lit(1),
                },
                TbStep::Step(2),
                TbStep::Assert {
                    kind: TbAssertKind::Eq,
                    left: TbValue::Port("count".into()),
                    right: TbValue::Lit(2),
                    loc: "counter_test.volt:5".into(),
                },
                TbStep::Reset,
                TbStep::Assert {
                    kind: TbAssertKind::False,
                    left: TbValue::Port("count".into()),
                    right: TbValue::Lit(0),
                    loc: "counter_test.volt:7".into(),
                },
            ],
        }];
        let cpp = test_testbench_cpp("Counter", &counter_ports(), &tests);
        assert!(cpp.contains("VOLT-TEST-BEGIN start_bit_is_low"));
        assert!(cpp.contains("VOLT-TEST-END start_bit_is_low ok"));
        assert!(cpp.contains("VOLT-ASSERT-FAIL assert_eq counter_test.volt:5"));
        assert!(cpp.contains("((unsigned long long)dut.count) == (2ULL)"));
        assert!(cpp.contains("((unsigned long long)dut.count) == 0"));
        // Her test taze DUT kurar ve reset uygular.
        assert!(cpp.contains("static bool test_0()"));
        assert!(cpp.contains("VerilatedContext uctx;"));
        assert_eq!(cpp.matches("apply_reset(&dut, ctx);").count(), 2);
        assert!(cpp.contains("return failed == 0 ? 0 : 1;"));
    }

    #[test]
    fn test_tb_fresh_dut_per_test() {
        let mk = |name: &str| TbTest {
            name: name.into(),
            steps: vec![TbStep::Step(1)],
        };
        let cpp = test_testbench_cpp("Counter", &counter_ports(), &[mk("a"), mk("b")]);
        assert!(cpp.contains("test_0"));
        assert!(cpp.contains("test_1"));
        assert_eq!(cpp.matches("TOP dut(ctx);").count(), 2);
    }
}
