//! SDC / XDC metin üretimi testleri (ADR-0054): satır biçimleri, lehçe
//! farkı (`ASYNC_REG`), determinizm ve `syntax_check` kapısı.

use volt_hir::collect_constraints;
use volt_sdc_emit::{syntax_check, Dialect, EmitOpts};
use volt_syntax::{parse, FileId};

fn opts() -> EmitOpts {
    EmitOpts {
        source: "t.volt".into(),
        version: "0.1.0".into(),
    }
}

fn render(src: &str, module: &str, dialect: Dialect) -> String {
    let parsed = parse(FileId(0), src);
    assert!(parsed.diagnostics.is_empty(), "{:?}", parsed.error_codes());
    let r = collect_constraints(&parsed.ast);
    assert!(r.diagnostics.is_empty(), "{:?}", r.diagnostics);
    let mc = r
        .modules
        .iter()
        .find(|m| m.module == module)
        .unwrap_or_else(|| panic!("modül {module} yok"));
    dialect.render(mc, &opts())
}

const MULTI: &str = "domain Fast { clock = posedge, frequency = 100.mhz }\n\
                     domain Slow { clock = posedge, frequency = 25_175.khz }\n\
                     @timing(max_delay(a, y) <= 5.ns)\n\
                     @multicycle(from = a, to = r, cycles = 3)\n\
                     module M {\n    in fast_clk : clock @Fast\n    in slow_clk : clock @Slow\n    in a : u8 @Fast\n    out y : u8 @Slow\n    \
                     reg r : u8 = 0\n    on fast_clk { r <= a }\n    y = sync(r, slow_clk)\n}\n";

#[test]
fn header_has_generator_source_and_do_not_edit() {
    let s = render(MULTI, "M", Dialect::Sdc);
    let head: Vec<&str> = s.lines().take(4).collect();
    assert_eq!(
        head,
        vec![
            "# Generated by Volt 0.1.0",
            "# Source: t.volt",
            "# DO NOT EDIT",
            "# Module: M"
        ]
    );
}

#[test]
fn create_clock_period_100mhz_is_10_000_and_25_175khz_is_39_722() {
    let s = render(MULTI, "M", Dialect::Sdc);
    assert!(
        s.contains("create_clock -name fast_clk -period 10.000 [get_ports fast_clk]"),
        "{s}"
    );
    assert!(
        s.contains("create_clock -name slow_clk -period 39.722 [get_ports slow_clk]"),
        "{s}"
    );
}

#[test]
fn clock_groups_asynchronous_between_domains() {
    let s = render(MULTI, "M", Dialect::Sdc);
    let expected = "set_clock_groups -asynchronous \\\n    -group [get_clocks {fast_clk}] \\\n    -group [get_clocks {slow_clk}]\n";
    assert!(s.contains(expected), "{s}");
}

#[test]
fn sync_bridge_gets_false_path_into_stage0() {
    let s = render(MULTI, "M", Dialect::Sdc);
    assert!(
        s.contains(
            "set_false_path -from [get_cells {r_reg*}] -to [get_cells {sync_r_stage0_reg*}]"
        ),
        "{s}"
    );
    assert!(!s.contains("ASYNC_REG"), "SDC lehçesinde ASYNC_REG yok");
}

#[test]
fn xdc_adds_async_reg_property_on_synchronizer_chain() {
    let s = render(MULTI, "M", Dialect::Xdc);
    assert!(
        s.contains(
            "set_property ASYNC_REG TRUE [get_cells {sync_r_stage0_reg* sync_r_stage1_reg*}]"
        ),
        "{s}"
    );
    assert!(s.contains("# Dialect: XDC"), "{s}");
}

#[test]
fn xdc_and_sdc_differ_only_in_header_and_async_reg() {
    let sdc = render(MULTI, "M", Dialect::Sdc);
    let xdc = render(MULTI, "M", Dialect::Xdc);
    let strip = |s: &str| {
        s.lines()
            .filter(|l| !l.starts_with("# Dialect:") && !l.starts_with("set_property ASYNC_REG"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    assert_eq!(strip(&sdc), strip(&xdc));
}

#[test]
fn max_delay_and_multicycle_lines() {
    let s = render(MULTI, "M", Dialect::Sdc);
    assert!(
        s.contains("set_max_delay 5.000 -from [get_ports a] -to [get_ports y]"),
        "{s}"
    );
    assert!(
        s.contains("set_multicycle_path 3 -setup -from [get_ports a] -to [get_cells {r_reg*}]"),
        "{s}"
    );
    assert!(
        s.contains("set_multicycle_path 2 -hold -from [get_ports a] -to [get_cells {r_reg*}]"),
        "{s}"
    );
}

#[test]
fn multicycle_of_one_has_no_hold_line() {
    let src = "module M {\n    in clk : clock\n    in a : u8\n    out y : u8\n    @multicycle(1)\n    reg r : u8 = 0\n    on clk { r <= a }\n    y = r\n}\n";
    let s = render(src, "M", Dialect::Sdc);
    assert!(
        s.contains("set_multicycle_path 1 -setup -to [get_cells {r_reg*}]"),
        "{s}"
    );
    assert!(!s.contains("-hold"), "{s}");
}

#[test]
fn clock_without_frequency_is_a_comment_not_a_command() {
    let src = "module M {\n    in clk : clock\n    in a : u8\n    out y : u8\n    y = a\n}\n";
    let s = render(src, "M", Dialect::Sdc);
    assert!(!s.lines().any(|l| l.starts_with("create_clock")), "{s}");
    assert!(
        s.contains("# clk: domain 'clk' has no frequency -- no create_clock (W0022)"),
        "{s}"
    );
}

#[test]
fn single_clock_has_no_clock_groups() {
    let src = "domain D { clock = posedge, frequency = 50.mhz }\nmodule M {\n    in clk : clock @D\n    in a : u8\n    out y : u8\n    y = a\n}\n";
    let s = render(src, "M", Dialect::Sdc);
    assert!(
        s.contains("create_clock -name clk -period 20.000 [get_ports clk]"),
        "{s}"
    );
    assert!(!s.contains("set_clock_groups"), "{s}");
}

#[test]
fn hierarchical_names_use_slash_prefix() {
    let src = "domain Fast { clock = posedge, frequency = 100.mhz }\ndomain Slow { clock = posedge, frequency = 50.mhz }\n\
               module Sub {\n    in f : clock @Fast\n    in s : clock @Slow\n    in a : bool @Fast\n    out y : bool @Slow\n    y = sync(a, s)\n}\n\
               module Top {\n    in fast_clk : clock @Fast\n    in slow_clk : clock @Slow\n    in x : bool @Fast\n    out y : bool @Slow\n    let u = Sub { f: fast_clk, s: slow_clk, a: x }\n    y = u.y\n}\n";
    let s = render(src, "Top", Dialect::Xdc);
    assert!(s.contains("-to [get_cells {u/sync_a_stage0_reg*}]"), "{s}");
    assert!(
        s.contains("[get_cells {u/sync_a_stage0_reg* u/sync_a_stage1_reg*}]"),
        "{s}"
    );
}

#[test]
fn output_is_deterministic() {
    assert_eq!(
        render(MULTI, "M", Dialect::Sdc),
        render(MULTI, "M", Dialect::Sdc)
    );
}

#[test]
fn output_path_is_constraints_module_extension() {
    let p = Dialect::Xdc.output_path(std::path::Path::new("build"), "VgaTop");
    assert_eq!(
        p,
        std::path::Path::new("build")
            .join("constraints")
            .join("VgaTop.xdc")
    );
    assert_eq!(Dialect::Sdc.flag(), "sdc");
}

// ═══ syntax_check ═════════════════════════════════════════════════

#[test]
fn generated_text_passes_syntax_check_in_both_dialects() {
    let sdc = render(MULTI, "M", Dialect::Sdc);
    let n = syntax_check(&sdc).unwrap_or_else(|e| panic!("{e}\n{sdc}"));
    // 2 create_clock + 1 clock_groups + 1 false_path + 1 max_delay + 2 multicycle
    assert_eq!(n, 7);
    let xdc = render(MULTI, "M", Dialect::Xdc);
    assert_eq!(syntax_check(&xdc).unwrap(), 8);
}

#[test]
fn syntax_check_rejects_unknown_command_unbalanced_and_bad_number() {
    assert!(syntax_check("frobnicate x\n")
        .unwrap_err()
        .contains("unknown command"));
    assert!(
        syntax_check("create_clock -name a -period 10.000 [get_ports a\n")
            .unwrap_err()
            .contains("unclosed")
    );
    assert!(
        syntax_check("set_max_delay 5 -from [get_ports a]\n").is_ok(),
        "tamsayı gecikme geçerli Tcl"
    );
    assert!(syntax_check("set_max_delay 5.0 -from [get_ports a]\n")
        .unwrap_err()
        .contains("d.ddd"));
    assert!(syntax_check("set_false_path\n")
        .unwrap_err()
        .contains("-from and/or -to"));
    assert!(syntax_check("set_clock_groups -asynchronous \\\n")
        .unwrap_err()
        .contains("unterminated"));
}
