//! Metin üretimi: SDC / XDC satırları ve üretilen metnin sözdizimi
//! denetimi (`syntax_check` — araç olmadan koşan test kapısı).

use volt_hir::constraints::format_ps;
use volt_hir::{Bridge, ClockConstraint, ModuleConstraints, PathKind, PathRule, Target};

use crate::{Dialect, EmitOpts};

/// Tcl satır devamı — `set_clock_groups` gibi uzun komutlar için.
const CONT: &str = " \\\n    ";

/// Modelin tam metni (başlık + bölümler).
pub fn render(mc: &ModuleConstraints, dialect: Dialect, opts: &EmitOpts) -> String {
    let mut out = header(mc, dialect, opts);
    clocks_section(mc, &mut out);
    groups_section(mc, &mut out);
    bridges_section(mc, dialect, &mut out);
    paths_section(mc, &mut out);
    out
}

fn header(mc: &ModuleConstraints, dialect: Dialect, opts: &EmitOpts) -> String {
    let kind = match dialect {
        Dialect::Sdc => "SDC (Synopsys Design Constraints)",
        Dialect::Xdc => "XDC (Xilinx Design Constraints, Vivado)",
    };
    format!(
        "# Generated by Volt {}\n# Source: {}\n# DO NOT EDIT\n# Module: {}\n# Dialect: {kind}\n# Units: time in ns, frequencies in Hz (comments)\n",
        opts.version, opts.source, mc.module
    )
}

fn clocks_section(mc: &ModuleConstraints, out: &mut String) {
    out.push_str("\n# ── Clocks (from domain frequency / @timing) ──\n");
    for c in &mc.clocks {
        match c.period_ps() {
            Some(ps) => out.push_str(&create_clock(c, ps)),
            None => out.push_str(&format!(
                "# {}: domain '{}' has no frequency -- no create_clock (W0022)\n",
                c.port, c.domain
            )),
        }
    }
}

fn create_clock(c: &ClockConstraint, ps: u64) -> String {
    let source = match c.freq_source {
        Some(volt_hir::constraints::FreqSource::Timing) => "@timing",
        _ => "domain",
    };
    let edge = match c.edge {
        volt_ast::ClockEdge::Negedge => " (negedge domain: registers sample the falling edge)",
        _ => "",
    };
    let mut s = format!(
        "# {}: domain '{}', {} Hz from {source}{edge}\n",
        c.port,
        c.domain,
        c.freq_hz.unwrap_or(0)
    );
    s.push_str(&format!(
        "create_clock -name {0} -period {1} [get_ports {0}]\n",
        c.port,
        format_ps(ps)
    ));
    s
}

fn groups_section(mc: &ModuleConstraints, out: &mut String) {
    let groups = mc.async_groups();
    if mc.clocks.len() < 2 {
        return;
    }
    out.push_str("\n# ── Clock groups (each domain is asynchronous to the others) ──\n");
    if groups.is_empty() {
        out.push_str(
            "# fewer than two clocks have a frequency -- no set_clock_groups (see W0022)\n",
        );
        return;
    }
    out.push_str("set_clock_groups -asynchronous");
    for g in &groups {
        out.push_str(CONT);
        out.push_str("-group [get_clocks {");
        out.push_str(&g.join(" "));
        out.push_str("}]");
    }
    out.push('\n');
}

fn bridges_section(mc: &ModuleConstraints, dialect: Dialect, out: &mut String) {
    if mc.bridges.is_empty() {
        return;
    }
    out.push_str(
        "\n# ── CDC bridges (generated synchronizers; paths into them are not timed) ──\n",
    );
    for b in &mc.bridges {
        bridge(b, dialect, out);
    }
}

fn bridge(b: &Bridge, dialect: Dialect, out: &mut String) {
    out.push_str(&format!(
        "# {} '{}': {} -> {}\n",
        b.kind,
        b.name,
        b.from_clock.as_deref().unwrap_or("?"),
        b.to_clock.as_deref().unwrap_or("?")
    ));
    for r in &b.rules {
        out.push_str(&path_rule(r));
    }
    if dialect == Dialect::Xdc && !b.async_regs.is_empty() {
        let cells: Vec<String> = b.async_regs.iter().map(|r| format!("{r}_reg*")).collect();
        out.push_str(&format!(
            "set_property ASYNC_REG TRUE [get_cells {{{}}}]\n",
            cells.join(" ")
        ));
    }
}

fn paths_section(mc: &ModuleConstraints, out: &mut String) {
    if mc.paths.is_empty() {
        return;
    }
    out.push_str("\n# ── Path constraints (@timing / @false_path / @multicycle) ──\n");
    for p in &mc.paths {
        out.push_str(&format!("# {}\n", p.comment));
        out.push_str(&path_rule(p));
    }
}

/// Tek kural → bir (multicycle'da iki) SDC komutu.
fn path_rule(r: &PathRule) -> String {
    let ends = endpoints(r);
    match r.kind {
        PathKind::FalsePath => format!("set_false_path{ends}\n"),
        PathKind::MaxDelay(ps) => format!("set_max_delay {}{ends}\n", format_ps(ps)),
        PathKind::MinDelay(ps) => format!("set_min_delay {}{ends}\n", format_ps(ps)),
        PathKind::Multicycle(n) => {
            let mut s = format!("set_multicycle_path {n} -setup{ends}\n");
            if n >= 2 {
                s.push_str(&format!("set_multicycle_path {} -hold{ends}\n", n - 1));
            }
            s
        }
    }
}

fn endpoints(r: &PathRule) -> String {
    let mut s = String::new();
    if let Some(f) = &r.from {
        s.push_str(" -from ");
        s.push_str(&target(f));
    }
    if let Some(t) = &r.to {
        s.push_str(" -to ");
        s.push_str(&target(t));
    }
    s
}

/// Uç noktanın Tcl sorgusu.
pub fn target(t: &Target) -> String {
    match t {
        Target::Port(n) => format!("[get_ports {n}]"),
        Target::Cells(n) => format!("[get_cells {{{n}_reg*}}]"),
        Target::Pin(n) => format!("[get_pins {{{n}}}]"),
        Target::Clock(n) => format!("[get_clocks {n}]"),
    }
}

/// Üretilen metnin sözdizimi denetimi: her mantıksal satır (Tcl `\`
/// devamı birleştirilmiş) ya yorum/boş ya da bilinen bir SDC komutuyla
/// başlar; `[]`/`{}` dengeli; sayısal argümanlar `d.ddd` biçiminde.
/// Hata metni döner (`Err`), temizse `Ok(komut sayısı)`. Dış araç
/// (OpenSTA/Vivado) olmadan koşan test kapısıdır; araçlı doğrulama
/// ADR-0054 §7'de.
pub fn syntax_check(text: &str) -> Result<usize, String> {
    const COMMANDS: &[&str] = &[
        "create_clock",
        "set_clock_groups",
        "set_false_path",
        "set_max_delay",
        "set_min_delay",
        "set_multicycle_path",
        "set_property",
    ];
    let mut logical: Vec<(usize, String)> = Vec::new();
    let mut pending: Option<(usize, String)> = None;
    for (i, raw) in text.lines().enumerate() {
        let line_no = i + 1;
        match pending.take() {
            Some((start, mut acc)) => {
                acc.push(' ');
                acc.push_str(raw.trim());
                if let Some(stripped) = acc.strip_suffix('\\') {
                    pending = Some((start, stripped.to_string()));
                } else {
                    logical.push((start, acc));
                }
            }
            None => {
                let t = raw.trim();
                if let Some(stripped) = t.strip_suffix('\\') {
                    pending = Some((line_no, stripped.to_string()));
                } else {
                    logical.push((line_no, t.to_string()));
                }
            }
        }
    }
    if let Some((start, _)) = pending {
        return Err(format!("line {start}: unterminated line continuation"));
    }
    let mut count = 0;
    for (line_no, l) in &logical {
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        let cmd = l.split_whitespace().next().unwrap_or("");
        if !COMMANDS.contains(&cmd) {
            return Err(format!("line {line_no}: unknown command '{cmd}'"));
        }
        check_balanced(l).map_err(|e| format!("line {line_no}: {e}"))?;
        for tok in l.split_whitespace() {
            if tok.contains('.')
                && !tok.contains(['[', '{', '/', '*'])
                && tok.chars().all(|c| c.is_ascii_digit() || c == '.')
            {
                let (int, frac) = tok.split_once('.').unwrap();
                if int.is_empty() || frac.len() != 3 || !frac.chars().all(|c| c.is_ascii_digit()) {
                    return Err(format!("line {line_no}: number '{tok}' must be d.ddd"));
                }
            }
        }
        if cmd == "create_clock" && !(l.contains(" -period ") && l.contains("[get_ports ")) {
            return Err(format!(
                "line {line_no}: create_clock needs -period and [get_ports ...]"
            ));
        }
        if (cmd == "set_false_path"
            || cmd == "set_max_delay"
            || cmd == "set_min_delay"
            || cmd == "set_multicycle_path")
            && !(l.contains(" -from ") || l.contains(" -to "))
        {
            return Err(format!("line {line_no}: {cmd} needs -from and/or -to"));
        }
        count += 1;
    }
    Ok(count)
}

fn check_balanced(l: &str) -> Result<(), String> {
    let mut stack = Vec::new();
    for c in l.chars() {
        match c {
            '[' | '{' => stack.push(c),
            ']' if stack.pop() != Some('[') => return Err("unbalanced ']'".into()),
            '}' if stack.pop() != Some('{') => return Err("unbalanced '}'".into()),
            _ => {}
        }
    }
    if stack.is_empty() {
        Ok(())
    } else {
        Err(format!("unclosed '{}'", stack.last().unwrap()))
    }
}
