//! Metin üretimi: SDC / XDC satırları ve üretilen metnin sözdizimi
//! denetimi (`syntax_check` — araç olmadan koşan test kapısı).

use volt_hir::constraints::format_ps;
use volt_hir::{
    Bridge, ClockConstraint, Crossing, CrossingClass, ModuleConstraints, PathKind, PathRule, Target,
};

use crate::{Dialect, EmitOpts, SdcStyle};

/// Tcl satır devamı — `set_clock_groups` gibi uzun komutlar için.
const CONT: &str = " \\\n    ";

/// Modelin tam metni (başlık + bölümler).
pub fn render(mc: &ModuleConstraints, dialect: Dialect, opts: &EmitOpts) -> String {
    let mut out = header(mc, dialect, opts);
    clocks_section(mc, &mut out);
    match opts.style {
        SdcStyle::ClockGroups => groups_section(mc, &mut out),
        SdcStyle::Targeted => domains_note(mc, &mut out),
    }
    bridges_section(mc, dialect, opts.style, &mut out);
    resets_section(mc, dialect, &mut out);
    paths_section(mc, &mut out);
    out
}

fn header(mc: &ModuleConstraints, dialect: Dialect, opts: &EmitOpts) -> String {
    let kind = match dialect {
        Dialect::Sdc => "SDC (Synopsys Design Constraints)",
        Dialect::Xdc => "XDC (Xilinx Design Constraints, Vivado)",
    };
    let mut s = format!(
        "# Generated by Volt {}\n# Source: {}\n# DO NOT EDIT\n# Module: {}\n# Dialect: {kind}\n# Units: time in ns, frequencies in Hz (comments)\n",
        opts.version, opts.source, mc.module
    );
    if opts.style == SdcStyle::ClockGroups {
        s.push_str("# Style: clock-groups — paths between domains are NOT timed; see ADR-0065\n");
    }
    s
}

fn clocks_section(mc: &ModuleConstraints, out: &mut String) {
    out.push_str("\n# ── Clocks (from domain frequency / @timing) ──\n");
    for c in &mc.clocks {
        match c.period_ps() {
            Some(ps) => out.push_str(&create_clock(c, ps)),
            None => out.push_str(&format!(
                "# {}: domain '{}' has no frequency -- no create_clock (W0022)\n",
                c.port, c.domain
            )),
        }
    }
}

fn create_clock(c: &ClockConstraint, ps: u64) -> String {
    let source = match c.freq_source {
        Some(volt_hir::constraints::FreqSource::Timing) => "@timing",
        _ => "domain",
    };
    let edge = match c.edge {
        volt_ast::ClockEdge::Negedge => " (negedge domain: registers sample the falling edge)",
        _ => "",
    };
    let mut s = format!(
        "# {}: domain '{}', {} Hz from {source}{edge}\n",
        c.port,
        c.domain,
        c.freq_hz.unwrap_or(0)
    );
    s.push_str(&format!(
        "create_clock -name {0} -period {1} [get_ports {0}]\n",
        c.port,
        format_ps(ps)
    ));
    s
}

fn groups_section(mc: &ModuleConstraints, out: &mut String) {
    let groups = mc.async_groups();
    if mc.clocks.len() < 2 {
        return;
    }
    out.push_str("\n# ── Clock groups (each domain is asynchronous to the others) ──\n");
    if groups.is_empty() {
        out.push_str(
            "# fewer than two clocks have a frequency -- no set_clock_groups (see W0022)\n",
        );
        return;
    }
    out.push_str("set_clock_groups -asynchronous");
    for g in &groups {
        out.push_str(CONT);
        out.push_str("-group [get_clocks {");
        out.push_str(&g.join(" "));
        out.push_str("}]");
    }
    out.push('\n');
}

/// Hedefli stil (ADR-0065 §4): iki ya da daha çok alan varken saat grubu
/// YAZILMADIĞINI açıklayan yorum. Tek alanlı modülün çıktısı değişmez.
fn domains_note(mc: &ModuleConstraints, out: &mut String) {
    if mc.groups.len() < 2 {
        return;
    }
    out.push_str("\n# ── Clock domains (no set_clock_groups; ADR-0065) ──\n");
    out.push_str(
        "# Paths between domains are timed. Only the path into each generated\n\
         # synchronizer's first stage is constrained below: a crossing without a\n\
         # synchronizer is reported by the timing tool, not hidden.\n",
    );
}

fn bridges_section(mc: &ModuleConstraints, dialect: Dialect, style: SdcStyle, out: &mut String) {
    if mc.bridges.is_empty() {
        return;
    }
    // Tek alanlı modülde (ör. asenkron pad girişinin sync()'i) iki stil
    // aynı kısıtı üretir; başlık da değişmez (ADR-0065 §4.2).
    let targeted = style == SdcStyle::Targeted && mc.groups.len() >= 2;
    out.push_str(if targeted {
        "\n# ── CDC bridges (generated synchronizers; only the path into the first stage is constrained) ──\n"
    } else {
        "\n# ── CDC bridges (generated synchronizers; paths into them are not timed) ──\n"
    });
    for b in &mc.bridges {
        bridge(mc, b, dialect, style, out);
    }
}

fn bridge(mc: &ModuleConstraints, b: &Bridge, dialect: Dialect, style: SdcStyle, out: &mut String) {
    out.push_str(&format!(
        "# {} '{}': {} -> {}\n",
        b.kind,
        b.name,
        b.from_clock.as_deref().unwrap_or("?"),
        b.to_clock.as_deref().unwrap_or("?")
    ));
    for r in &b.rules {
        match (style, &r.crossing) {
            (SdcStyle::Targeted, Some(c)) => out.push_str(&crossing_rule(mc, r, c, dialect)),
            _ => out.push_str(&path_rule(r)),
        }
    }
    if dialect == Dialect::Xdc && !b.async_regs.is_empty() {
        out.push_str(&async_reg(&b.async_regs));
    }
}

/// `set_property ASYNC_REG TRUE` — XDC, senkronizör zinciri register'ları.
fn async_reg(regs: &[String]) -> String {
    let cells: Vec<String> = regs.iter().map(|r| format!("{r}_reg*")).collect();
    format!(
        "set_property ASYNC_REG TRUE [get_cells {{{}}}]\n",
        cells.join(" ")
    )
}

/// Hedefli stilde bir köprü geçişi (ADR-0065 §4.2 tablosu). Tek bitlik
/// kontrol ve veri geçişi genel `.sdc`'de false path; XDC'de kontrol
/// geçişi `set_max_delay -datapath_only T_src`. Gray işaretçi `.sdc`'de
/// `-ignore_clock_latency`, XDC'de `-datapath_only` + `set_bus_skew`.
/// Kaynak saatin periyodu bilinmiyorsa false path'e düşer (frekanssız
/// kaynak saatte bir yorum satırıyla).
fn crossing_rule(mc: &ModuleConstraints, r: &PathRule, c: &Crossing, dialect: Dialect) -> String {
    let bounded = match (c.class, dialect) {
        (CrossingClass::Data, _) | (CrossingClass::Control, Dialect::Sdc) => false,
        (CrossingClass::Control, Dialect::Xdc) | (CrossingClass::Gray, _) => true,
    };
    if !bounded {
        return path_rule(r);
    }
    let period = c
        .src_clock
        .as_deref()
        .and_then(|clk| mc.clocks.iter().find(|k| k.port == clk))
        .and_then(ClockConstraint::period_ps);
    let Some(ps) = period else {
        // Kaynak saat yoksa (alansız giriş portu, asenkron pad) bağlanacak
        // bir periyot da yoktur: false path doğru kısıttır.
        return match &c.src_clock {
            Some(clk) => format!(
                "# source clock '{clk}' has no frequency (W0022) -- set_false_path instead of set_max_delay\n{}",
                path_rule(r)
            ),
            None => path_rule(r),
        };
    };
    let ends = endpoints(r);
    let t = format_ps(ps);
    match (c.class, dialect) {
        (CrossingClass::Gray, Dialect::Sdc) => {
            format!("set_max_delay -ignore_clock_latency {t}{ends}\n")
        }
        (CrossingClass::Gray, Dialect::Xdc) => {
            format!("set_max_delay -datapath_only {t}{ends}\nset_bus_skew{ends} {t}\n")
        }
        _ => format!("set_max_delay -datapath_only {t}{ends}\n"),
    }
}

/// Ham reset portları ve bırakma senkronizörleri (ADR-0065 §4.2, §4.4):
/// yalnız ham portun etkinleşme yolu (tanım gereği asenkron, yalnız zincir
/// temizleme pinlerini sürer) kapanır; zincir çıkışından register'ların
/// temizleme pinlerine giden bırakma yolu recovery/removal olarak
/// zamanlanır. Her iki stilde üretilir.
fn resets_section(mc: &ModuleConstraints, dialect: Dialect, out: &mut String) {
    if mc.raw_resets.is_empty() && mc.reset_chains.is_empty() {
        return;
    }
    out.push_str("\n# ── Reset synchronizers (raw reset ports; ADR-0065) ──\n");
    for port in &mc.raw_resets {
        out.push_str(&format!(
            "# {port}: raw reset; its assert path into the synchronizers is not timed,\n\
             # the synchronized release is timed as recovery/removal\n\
             set_false_path -from [get_ports {port}]\n"
        ));
    }
    for c in &mc.reset_chains {
        let base = c
            .stages
            .first()
            .map_or("", |s| s.strip_suffix("_stage0").unwrap_or(s));
        out.push_str(&format!(
            "# {base}: {} -> {} ({} stages)\n",
            c.raw_port,
            c.clock.as_deref().unwrap_or("?"),
            c.stages.len()
        ));
        if dialect == Dialect::Xdc {
            out.push_str(&async_reg(&c.stages));
        }
    }
}

fn paths_section(mc: &ModuleConstraints, out: &mut String) {
    if mc.paths.is_empty() {
        return;
    }
    out.push_str("\n# ── Path constraints (@timing / @false_path / @multicycle) ──\n");
    for p in &mc.paths {
        out.push_str(&format!("# {}\n", p.comment));
        out.push_str(&path_rule(p));
    }
}

/// Tek kural → bir (multicycle'da iki) SDC komutu.
fn path_rule(r: &PathRule) -> String {
    let ends = endpoints(r);
    match r.kind {
        PathKind::FalsePath => format!("set_false_path{ends}\n"),
        PathKind::MaxDelay(ps) => format!("set_max_delay {}{ends}\n", format_ps(ps)),
        PathKind::MinDelay(ps) => format!("set_min_delay {}{ends}\n", format_ps(ps)),
        PathKind::Multicycle(n) => {
            let mut s = format!("set_multicycle_path {n} -setup{ends}\n");
            if n >= 2 {
                s.push_str(&format!("set_multicycle_path {} -hold{ends}\n", n - 1));
            }
            s
        }
    }
}

fn endpoints(r: &PathRule) -> String {
    let mut s = String::new();
    if let Some(f) = &r.from {
        s.push_str(" -from ");
        s.push_str(&target(f));
    }
    if let Some(t) = &r.to {
        s.push_str(" -to ");
        s.push_str(&target(t));
    }
    s
}

/// Uç noktanın Tcl sorgusu.
pub fn target(t: &Target) -> String {
    match t {
        Target::Port(n) => format!("[get_ports {n}]"),
        Target::Cells(n) => format!("[get_cells {{{n}_reg*}}]"),
        Target::Pin(n) => format!("[get_pins {{{n}}}]"),
        Target::Clock(n) => format!("[get_clocks {n}]"),
    }
}

/// Üretilen metnin sözdizimi denetimi: her mantıksal satır (Tcl `\`
/// devamı birleştirilmiş) ya yorum/boş ya da bilinen bir SDC komutuyla
/// başlar; `[]`/`{}` dengeli; sayısal argümanlar `d.ddd` biçiminde.
/// Hata metni döner (`Err`), temizse `Ok(komut sayısı)`. Dış araç
/// (OpenSTA/Vivado) olmadan koşan test kapısıdır; araçlı doğrulama
/// ADR-0054 §7'de.
pub fn syntax_check(text: &str) -> Result<usize, String> {
    const COMMANDS: &[&str] = &[
        "create_clock",
        "set_clock_groups",
        "set_false_path",
        "set_max_delay",
        "set_min_delay",
        "set_multicycle_path",
        "set_property",
        "set_bus_skew",
    ];
    let mut logical: Vec<(usize, String)> = Vec::new();
    let mut pending: Option<(usize, String)> = None;
    for (i, raw) in text.lines().enumerate() {
        let line_no = i + 1;
        match pending.take() {
            Some((start, mut acc)) => {
                acc.push(' ');
                acc.push_str(raw.trim());
                if let Some(stripped) = acc.strip_suffix('\\') {
                    pending = Some((start, stripped.to_string()));
                } else {
                    logical.push((start, acc));
                }
            }
            None => {
                let t = raw.trim();
                if let Some(stripped) = t.strip_suffix('\\') {
                    pending = Some((line_no, stripped.to_string()));
                } else {
                    logical.push((line_no, t.to_string()));
                }
            }
        }
    }
    if let Some((start, _)) = pending {
        return Err(format!("line {start}: unterminated line continuation"));
    }
    let mut count = 0;
    for (line_no, l) in &logical {
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        let cmd = l.split_whitespace().next().unwrap_or("");
        if !COMMANDS.contains(&cmd) {
            return Err(format!("line {line_no}: unknown command '{cmd}'"));
        }
        check_balanced(l).map_err(|e| format!("line {line_no}: {e}"))?;
        for tok in l.split_whitespace() {
            if tok.contains('.')
                && !tok.contains(['[', '{', '/', '*'])
                && tok.chars().all(|c| c.is_ascii_digit() || c == '.')
            {
                let (int, frac) = tok.split_once('.').unwrap();
                if int.is_empty() || frac.len() != 3 || !frac.chars().all(|c| c.is_ascii_digit()) {
                    return Err(format!("line {line_no}: number '{tok}' must be d.ddd"));
                }
            }
        }
        if cmd == "create_clock" && !(l.contains(" -period ") && l.contains("[get_ports ")) {
            return Err(format!(
                "line {line_no}: create_clock needs -period and [get_ports ...]"
            ));
        }
        if (cmd == "set_false_path"
            || cmd == "set_max_delay"
            || cmd == "set_min_delay"
            || cmd == "set_multicycle_path"
            || cmd == "set_bus_skew")
            && !(l.contains(" -from ") || l.contains(" -to "))
        {
            return Err(format!("line {line_no}: {cmd} needs -from and/or -to"));
        }
        count += 1;
    }
    Ok(count)
}

fn check_balanced(l: &str) -> Result<(), String> {
    let mut stack = Vec::new();
    for c in l.chars() {
        match c {
            '[' | '{' => stack.push(c),
            ']' if stack.pop() != Some('[') => return Err("unbalanced ']'".into()),
            '}' if stack.pop() != Some('{') => return Err("unbalanced '}'".into()),
            _ => {}
        }
    }
    if stack.is_empty() {
        Ok(())
    } else {
        Err(format!("unclosed '{}'", stack.last().unwrap()))
    }
}
