// AXI4-Lite register slave written with the builtin Handshake<T> bundle
// (ADR-0050) on top of bundle ports (ADR-0039).
//
// Each AXI channel is one `Handshake<Payload>`: the payload struct
// carries the channel's data fields and the bundle adds valid/ready.
// The request channels are consumed (`in aw` flips data/valid into
// inputs and ready into an output), the response channels are produced
// (`out b`, `out r`). The generated SystemVerilog is flat — aw_data_addr,
// aw_data_prot, aw_valid, aw_ready, ... — no interface/modport.
//
// Register map (full 32-bit address compare):
//   0x00 reg0   RW    0x04 reg1   RW    0x08 reg2   RW    0x0C reg3   RW
//   0x10 status RO (input port)         other addresses read as zero
//
// Protocol: the write channels are accepted together (aw.ready and
// w.ready rise only when both aw.valid and w.valid are high, which
// AXI4-Lite permits), the write happens on that edge and b.valid holds
// until the master raises b.ready. Reads are accepted whenever no read
// response is pending; r.valid holds until r.ready. Byte strobes are
// honoured through a write mask. The registers accept only secure,
// unprivileged data accesses (prot == 0): any other access is refused,
// the write is dropped and the response is SLVERR (2); accepted
// accesses respond OKAY (0).
//
// The valid/ready rules themselves — valid held until ready, payload
// stable while stalled — are generated by the compiler for every
// Handshake port: assumptions on the request channels (the master's
// obligation, which a slave cannot enforce on its inputs), proven
// invariants on the response channels.

pub struct AxiAddr  { addr : u32, prot : u3 }
pub struct AxiWData { data : u32, strb : u4 }
pub struct AxiResp  { resp : u2 }
pub struct AxiRData { data : u32, resp : u2 }

pub module Axi4LiteSlave {
    in  clk    : clock
    in  aw     : Handshake<AxiAddr>
    in  w      : Handshake<AxiWData>
    out b      : Handshake<AxiResp>
    in  ar     : Handshake<AxiAddr>
    out r      : Handshake<AxiRData>
    in  status : u32
    out reg0   : u32
    out reg1   : u32
    out reg2   : u32
    out reg3   : u32

    // Both write channels are accepted in the same cycle.
    invariant: aw.ready == w.ready
    // No new write is accepted while a write response is pending.
    invariant: b.valid -> !aw.ready
    // No new read is accepted while a read response is pending.
    invariant: r.valid -> !ar.ready
    // Responses are OKAY or SLVERR, never EXOKAY/DECERR.
    invariant: b.data.resp == 0 || b.data.resp == 2
    invariant: r.data.resp == 0 || r.data.resp == 2
    // Every accepted request is answered on the very next cycle.
    invariant: prev(aw.fired) -> b.valid
    invariant: prev(ar.fired) -> r.valid

    cover: b.fired
    cover: r.fired
    cover: b.valid && b.data.resp == 2
    cover: reg3 != 0

    reg reg0_r   : u32  = 0
    reg reg1_r   : u32  = 0
    reg reg2_r   : u32  = 0
    reg reg3_r   : u32  = 0
    reg bvalid_r : bool = false
    reg berr_r   : bool = false
    reg rvalid_r : bool = false
    reg rerr_r   : bool = false
    reg rdata_r  : u32  = 0

    let wr_fire : bool = aw.valid && w.valid && !bvalid_r
    let rd_fire : bool = ar.valid && !rvalid_r
    let wmask : u32 = (if w.data.strb[0] { 0x000000FF } else { 0 })
                    | (if w.data.strb[1] { 0x0000FF00 } else { 0 })
                    | (if w.data.strb[2] { 0x00FF0000 } else { 0 })
                    | (if w.data.strb[3] { 0xFF000000 } else { 0 })
    let wdata : u32 = w.data.data & wmask

    on clk {
        if wr_fire {
            bvalid_r <= true
            berr_r   <= aw.data.prot != 0
            if aw.data.prot == 0 {
                match aw.data.addr {
                    0x0 => { reg0_r <= (reg0_r & ~wmask) | wdata }
                    0x4 => { reg1_r <= (reg1_r & ~wmask) | wdata }
                    0x8 => { reg2_r <= (reg2_r & ~wmask) | wdata }
                    0xC => { reg3_r <= (reg3_r & ~wmask) | wdata }
                    _ => { }
                }
            }
        }
        if b.fired {
            bvalid_r <= false
        }
        if rd_fire {
            rvalid_r <= true
            rerr_r   <= ar.data.prot != 0
            match ar.data.addr {
                0x0  => { rdata_r <= reg0_r }
                0x4  => { rdata_r <= reg1_r }
                0x8  => { rdata_r <= reg2_r }
                0xC  => { rdata_r <= reg3_r }
                0x10 => { rdata_r <= status }
                _ => { rdata_r <= 0 }
            }
        }
        if r.fired {
            rvalid_r <= false
        }
    }

    aw.ready    = wr_fire
    w.ready     = wr_fire
    b.valid     = bvalid_r
    b.data.resp = if berr_r { 2 } else { 0 }
    ar.ready    = rd_fire
    r.valid     = rvalid_r
    r.data.data = rdata_r
    r.data.resp = if rerr_r { 2 } else { 0 }
    reg0 = reg0_r
    reg1 = reg1_r
    reg2 = reg2_r
    reg3 = reg3_r
}
