[package]
name = "volt-hir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
volt-span = { path = "../volt-span" }
volt-diagnostics = { path = "../volt-diagnostics" }
volt-ast = { path = "../volt-ast" }

[dev-dependencies]
volt-syntax = { path = "../volt-syntax" }
