[package]
name = "volt-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "volt"
path = "src/main.rs"

[dependencies]
volt-ast = { path = "../volt-ast" }
volt-hir = { path = "../volt-hir" }
volt-lower = { path = "../volt-lower" }
volt-span = { path = "../volt-span" }
volt-syntax = { path = "../volt-syntax" }
volt-sv-emit = { path = "../volt-sv-emit" }
volt-diagnostics = { path = "../volt-diagnostics" }
volt-lsp = { path = "../volt-lsp" }
clap.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
