// This file was generated by Volt.
// Source:  table_test.volt
// Version: 0.1.0
//
// DO NOT EDIT — make changes in the source file instead.

`default_nettype none

module Table (
    input  logic              clk,
    input  logic              rst,
    input  logic              rst,
    input  logic [2:0]        addr,
    input  logic signed [7:0] sv,
    input  logic              we,
    output logic [7:0]        data,
    output logic signed [7:0] secho,
    output logic              wrote,
    output logic              empty
);

    logic [7:0] mem [0:7];
    logic [7:0] hits;

    always_ff @(posedge clk) begin
        if (rst) begin
            hits <= 8'd0;
        end else begin
            if (rst) begin
                hits <= 8'd0;
            end else if (we) begin
                hits <= hits + 8'd1;
            end
        end
    end

    assign data = mem[addr];
    assign secho = sv;
    assign wrote = hits > 8'd0;
    assign empty = hits == 8'd0;

endmodule

`default_nettype wire
