// This file was generated by Volt. DO NOT EDIT.
#include "VTable.h"
#include "verilated.h"
#include <cstdio>

using TOP = VTable;

#include <cstddef>
#include "VTable___024root.h"
#include <functional>
#include <vector>

// Script runtime (ADR-0058): faults fail the test instead of crashing.
static int volt_fault = 0;
static unsigned long long volt_fault_a = 0;
static unsigned long long volt_fault_b = 0;
static const char* volt_fault_name() {
    switch (volt_fault) {
        case 1: return "index_out_of_bounds";
        case 2: return "division_by_zero";
        case 3: return "load_too_long";
        default: return "load_value_too_wide";
    }
}
static unsigned long long volt_set_fault(int kind, unsigned long long a, unsigned long long b) {
    if (!volt_fault) { volt_fault = kind; volt_fault_a = a; volt_fault_b = b; }
    return 0;
}
static unsigned long long volt_at(const unsigned long long* data, std::size_t n, unsigned long long i) {
    return i < n ? data[i] : volt_set_fault(1, i, n);
}
static unsigned long long volt_div(unsigned long long a, unsigned long long b) {
    return b ? a / b : volt_set_fault(2, a, b);
}
static unsigned long long volt_rem(unsigned long long a, unsigned long long b) {
    return b ? a % b : volt_set_fault(2, a, b);
}
static unsigned long long volt_shl(unsigned long long a, unsigned long long b) {
    return b < 64 ? a << b : 0;
}
static unsigned long long volt_shr(unsigned long long a, unsigned long long b) {
    return b < 64 ? a >> b : 0;
}
template <typename T, std::size_t N>
static void volt_load(VlUnpacked<T, N>& dst, const unsigned long long* src, std::size_t n, unsigned bits) {
    if (n > N) { volt_set_fault(3, n, N); return; }
    for (std::size_t i = 0; i < n; ++i) {
        // bits == 0: element width unknown to the compiler, fall back to the C++ type.
        const bool fits = bits == 0 ? static_cast<unsigned long long>(static_cast<T>(src[i])) == src[i]
                                    : (bits >= 64 || (src[i] >> bits) == 0);
        if (!fits) { volt_set_fault(4, src[i], i); return; }
        dst[i] = static_cast<T>(src[i]);
    }
}

// Port width guard (ADR-0059): a value that does not fit fails the test.
static bool volt_port_fits(unsigned long long v, unsigned bits, bool is_signed) {
    if (bits >= 64) return true;
    const unsigned long long mask = (1ULL << bits) - 1;
    if ((v & ~mask) == 0) return true;
    // A negative number written as 0 - n: bits [63:bits-1] are all ones.
    return is_signed && (v | (mask >> 1)) == ~0ULL;
}
static unsigned long long volt_port_bits(unsigned long long v, unsigned bits) {
    return bits >= 64 ? v : v & ((1ULL << bits) - 1);
}
// Width unknown to the compiler: fall back to the C++ storage type.
template <typename T>
static bool volt_port_fits_type(const T&, unsigned long long v) {
    return static_cast<unsigned long long>(static_cast<T>(v)) == v;
}

static void run_cycle(TOP* dut, VerilatedContext* ctx) {
    dut->clk = 1;
    dut->eval();
    ctx->timeInc(1);
    dut->clk = 0;
    dut->eval();
    ctx->timeInc(1);
}

static void apply_reset(TOP* dut, VerilatedContext* ctx) {
    dut->rst = 1;
    run_cycle(dut, ctx);
    run_cycle(dut, ctx);
    dut->rst = 0;
}

static bool test_0() {
    VerilatedContext uctx;
    VerilatedContext* ctx = &uctx;
    TOP dut(ctx);
    volt_fault = 0;
    std::vector<std::function<void()>> volt_loads;
    dut.rst = 0;
    dut.addr = 0;
    dut.sv = 0;
    dut.we = 0;
    apply_reset(&dut, ctx);
    static const unsigned long long v_image[] = {
        0x3ULL, 0x1ULL, 0x4ULL, 0x1ULL, 0x5ULL, 0x9ULL, 0x2ULL, 0x6ULL,
    };
    static const std::size_t n_image = 8;
    { auto volt_l = [&dut]() { volt_load(dut.rootp->Table__DOT__mem, v_image, n_image, 8U); }; volt_l(); volt_loads.push_back(volt_l); }
    dut.eval();
    if (volt_fault) {
        std::printf("VOLT-ASSERT-FAIL %s table_test.volt:32 left=%llu right=%llu\n", volt_fault_name(), volt_fault_a, volt_fault_b);
        dut.final();
        return false;
    }
    dut.we = 0ULL;
    { const unsigned long long volt_lo_i = 0ULL, volt_hi_i = (unsigned long long)n_image;
    for (unsigned long long v_i = volt_lo_i; v_i < volt_hi_i; ++v_i) {
        { const unsigned long long volt_pv = v_i;
        if (!volt_port_fits(volt_pv, 3U, false)) {
            std::printf("VOLT-ASSERT-FAIL port_overflow table_test.volt:35 left=%llu right=%llu loop=i=%llu port=addr:u3\n", volt_pv, 3ULL, v_i);
            dut.final();
            return false;
        }
        dut.addr = volt_port_bits(volt_pv, 3U); }
        for (unsigned long long s = 0; s < 1ULL; ++s) run_cycle(&dut, ctx);
        { const unsigned long long volt_al = (unsigned long long)dut.data, volt_ar = volt_at(v_image, n_image, v_i);
        if (volt_fault) {
            std::printf("VOLT-ASSERT-FAIL %s table_test.volt:37 left=%llu right=%llu loop=i=%llu\n", volt_fault_name(), volt_fault_a, volt_fault_b, v_i);
            dut.final();
            return false;
        }
        if (!(volt_al == volt_ar)) {
            std::printf("VOLT-ASSERT-FAIL assert_eq table_test.volt:37 left=%llu right=%llu loop=i=%llu\n", volt_al, volt_ar, v_i);
            dut.final();
            return false;
        } }
    } }
    dut.final();
    return true;
}

static bool test_1() {
    VerilatedContext uctx;
    VerilatedContext* ctx = &uctx;
    TOP dut(ctx);
    volt_fault = 0;
    dut.rst = 0;
    dut.addr = 0;
    dut.sv = 0;
    dut.we = 0;
    apply_reset(&dut, ctx);
    dut.sv = 254ULL;
    dut.we = 1ULL;
    for (unsigned long long s = 0; s < 2ULL; ++s) run_cycle(&dut, ctx);
    if (!(((unsigned long long)dut.secho) != (0ULL))) {
        std::printf("VOLT-ASSERT-FAIL assert_ne table_test.volt:46 left=%llu right=%llu\n", (unsigned long long)dut.secho, 0ULL);
        dut.final();
        return false;
    }
    if (!(((unsigned long long)dut.wrote) != 0)) {
        std::printf("VOLT-ASSERT-FAIL assert_true table_test.volt:47 left=%llu right=%llu\n", (unsigned long long)dut.wrote, 0ULL);
        dut.final();
        return false;
    }
    if (!(((unsigned long long)dut.empty) == 0)) {
        std::printf("VOLT-ASSERT-FAIL assert_false table_test.volt:48 left=%llu right=%llu\n", (unsigned long long)dut.empty, 0ULL);
        dut.final();
        return false;
    }
    dut.final();
    return true;
}

int main(int, char**) {
    int failed = 0;
    std::printf("VOLT-TEST-BEGIN reads_back_loaded_table\n");
    if (test_0()) std::printf("VOLT-TEST-END reads_back_loaded_table ok\n");
    else { ++failed; std::printf("VOLT-TEST-END reads_back_loaded_table fail\n"); }
    std::printf("VOLT-TEST-BEGIN signed_echo_and_flags\n");
    if (test_1()) std::printf("VOLT-TEST-END signed_echo_and_flags ok\n");
    else { ++failed; std::printf("VOLT-TEST-END signed_echo_and_flags fail\n"); }
    return failed == 0 ? 0 : 1;
}
