//! C başlığı (ADR-0053 §C): `#define` adresleri/maskeleri ve
//! `static inline` erişimciler. Taban adres derleme zamanı sabitidir
//! (`<MOD>_BASE`); her erişim `*(volatile uint32_t *)` üzerinden yapılır.
//! ReadOnly alana setter, WriteOnly alana getter ÜRETİLMEZ.

use std::fmt::Write as _;

use volt_ast::mmio::{FieldDesc, FieldKind, RegAccess, RegDesc, RegMap};

use crate::names::{c_type, doc_lines, hex32_c, hex_short, upper_snake};
use crate::EmitOpts;

pub fn emit(map: &RegMap, opts: &EmitOpts) -> String {
    let guard = format!("{}_H", upper_snake(&map.module));
    let mod_up = upper_snake(&map.module);
    let mut s = String::new();
    let _ = writeln!(
        s,
        "/* `{}` register map -- generated by Volt HDL {} from {} (ADR-0053).\n \
         * Do not edit: regenerate with `volt build --emit=c {}`.\n \
         * Bus: {} (32-bit registers, byte offsets from {mod_up}_BASE).",
        map.module, opts.version, opts.source, opts.source, map.bus
    );
    doc_lines(&mut s, " ", "*", map.doc.as_deref());
    let _ = writeln!(
        s,
        " */\n#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n#include <stdbool.h>\n\n\
         #ifdef __cplusplus\nextern \"C\" {{\n#endif\n\n\
         #define {mod_up}_BASE {}\n",
        hex32_c(map.base)
    );
    for reg in &map.registers {
        register(&mut s, &mod_up, reg);
    }
    let _ = writeln!(s, "#ifdef __cplusplus\n}}\n#endif\n\n#endif /* {guard} */");
    s
}

fn access_name(a: RegAccess) -> &'static str {
    match a {
        RegAccess::ReadWrite => "ReadWrite",
        RegAccess::ReadOnly => "ReadOnly",
        RegAccess::WriteOnly => "WriteOnly",
    }
}

fn register(s: &mut String, mod_up: &str, reg: &RegDesc) {
    let up = format!("{mod_up}_{}", upper_snake(&reg.name));
    let lower = format!("{}_{}", mod_up.to_ascii_lowercase(), reg.name);
    let _ = writeln!(
        s,
        "/* {} @ {} ({}{}) */",
        reg.name,
        hex_short(reg.offset),
        access_name(reg.access),
        if reg.volatile { ", volatile" } else { "" }
    );
    if let Some(doc) = &reg.doc {
        for line in doc.lines() {
            let _ = writeln!(s, "/* {line} */");
        }
    }
    let _ = writeln!(
        s,
        "#define {up} ({mod_up}_BASE + {}U)\n#define {up}_OFFSET {}U\n#define {up}_MASK {}",
        hex_short(reg.offset),
        hex_short(reg.offset),
        hex32_c(u64::from(reg.read_mask()))
    );
    for f in reg.named() {
        let fup = format!("{up}_{}", upper_snake(&f.name));
        let _ = writeln!(
            s,
            "#define {fup}_SHIFT {}U\n#define {fup}_MASK 0x{:X}U",
            f.lsb,
            (1u64 << f.width) - 1
        );
    }
    s.push('\n');
    if reg.access.readable() {
        let _ = writeln!(
            s,
            "static inline uint32_t {lower}_read(void) {{\n    \
             return *(volatile uint32_t *){up} & {up}_MASK;\n}}"
        );
    }
    if reg.access.writable() {
        let _ = writeln!(
            s,
            "static inline void {lower}_write(uint32_t word) {{\n    \
             *(volatile uint32_t *){up} = word & {up}_MASK;\n}}"
        );
    }
    for f in reg.named() {
        field_fns(s, mod_up, reg, &up, f);
    }
    s.push('\n');
}

/// Okuma-değiştirme-yazmada korunan bitler (rust.rs ile aynı kural).
fn keep_mask(reg: &RegDesc, field: &FieldDesc) -> u32 {
    let pulses = reg
        .named()
        .filter(|f| f.self_clearing || f.w1c)
        .fold(0, |m, f| m | f.mask());
    reg.read_mask() & !field.mask() & !pulses
}

/// Okuma-değiştirme-yazma gövdesi; korunacak bit yoksa okuma atlanır.
fn rmw_body(up: &str, keep: u32, placed: &str) -> String {
    if keep == 0 {
        format!("*(volatile uint32_t *){up} = {placed};")
    } else {
        format!(
            "uint32_t word = *(volatile uint32_t *){up} & {};\n    \
             *(volatile uint32_t *){up} = word | {placed};",
            hex32_c(u64::from(keep))
        )
    }
}

fn field_fns(s: &mut String, mod_up: &str, reg: &RegDesc, up: &str, f: &FieldDesc) {
    let lower = mod_up.to_ascii_lowercase();
    let fup = format!("{up}_{}", upper_snake(&f.name));
    let name = format!("{}_{}", reg.name, f.name);
    let ty = c_type(f);
    let is_bool = f.kind == FieldKind::Bool;
    let doc = |s: &mut String| {
        if let Some(d) = &f.doc {
            for line in d.lines() {
                let _ = writeln!(s, "/* {line} */");
            }
        }
    };
    if reg.access.readable() {
        doc(s);
        let value = format!("(*(volatile uint32_t *){up} >> {fup}_SHIFT) & {fup}_MASK");
        let body = if is_bool {
            format!("return ({value}) != 0U;")
        } else if f.width >= 32 {
            format!("return {value};")
        } else {
            format!("return ({ty})({value});")
        };
        let _ = writeln!(
            s,
            "static inline {ty} {lower}_get_{name}(void) {{\n    {body}\n}}"
        );
    }
    let bit = hex32_c(u64::from(f.mask()));
    if f.self_clearing {
        doc(s);
        let body = if reg.access.readable() {
            rmw_body(up, keep_mask(reg, f), &bit)
        } else {
            format!("*(volatile uint32_t *){up} = {bit};")
        };
        let _ = writeln!(
            s,
            "/* self-clearing: high for one cycle */\n\
             static inline void {lower}_trigger_{name}(void) {{\n    {body}\n}}"
        );
        return;
    }
    if f.w1c {
        doc(s);
        let _ = writeln!(
            s,
            "/* write-1-to-clear: set by hardware */\n\
             static inline void {lower}_clear_{name}(void) {{\n    \
             *(volatile uint32_t *){up} = {bit};\n}}"
        );
        return;
    }
    if reg.access.writable() {
        doc(s);
        let placed = format!("(((uint32_t){} << {fup}_SHIFT) & {bit})", f.name);
        let body = if reg.access.readable() {
            rmw_body(up, keep_mask(reg, f), &placed)
        } else {
            format!(
                "/* WriteOnly register: the other fields are written as 0 */\n    \
                 *(volatile uint32_t *){up} = {placed};"
            )
        };
        let _ = writeln!(
            s,
            "static inline void {lower}_set_{name}({ty} {}) {{\n    {body}\n}}",
            f.name
        );
    }
}
