//! Markdown register haritası (ADR-0053 §Markdown): özet tablo
//! (`Offset | Name | Access | Description`) + her register için bit
//! alanı tablosu. Açıklamalar Volt doc yorumlarından gelir.

use std::fmt::Write as _;

use volt_ast::mmio::{RegAccess, RegDesc, RegMap};

use crate::names::{doc_summary, hex32_rust, hex_short, volt_type};
use crate::EmitOpts;

pub fn emit(map: &RegMap, opts: &EmitOpts) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# `{}` register map\n", map.module);
    if let Some(doc) = &map.doc {
        let _ = writeln!(s, "{doc}\n");
    }
    let _ = writeln!(
        s,
        "- Base address: `{}`\n- Bus: {} (32-bit registers, byte offsets)\n\
         - Source: `{}` — generated by Volt HDL {} (ADR-0053); do not edit.\n",
        hex32_rust(map.base),
        map.bus,
        opts.source,
        opts.version
    );
    let _ = writeln!(
        s,
        "## Registers\n\n| Offset | Name | Access | Description |\n|---|---|---|---|"
    );
    for r in &map.registers {
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {} | {} |",
            hex_short(r.offset),
            r.name,
            access_cell(r),
            doc_summary(r.doc.as_deref())
        );
    }
    s.push('\n');
    for r in &map.registers {
        register(&mut s, map, r);
    }
    s
}

fn access_cell(r: &RegDesc) -> String {
    let base = match r.access {
        RegAccess::ReadWrite => "RW",
        RegAccess::ReadOnly => "RO",
        RegAccess::WriteOnly => "WO",
    };
    if r.volatile {
        format!("{base}, volatile")
    } else {
        base.to_string()
    }
}

fn register(s: &mut String, map: &RegMap, r: &RegDesc) {
    let _ = writeln!(
        s,
        "### `{}` — offset `{}` (address `{}`), {}\n",
        r.name,
        hex_short(r.offset),
        hex32_rust(r.address(map.base)),
        access_cell(r)
    );
    if let Some(doc) = &r.doc {
        let _ = writeln!(s, "{doc}\n");
    }
    let _ = writeln!(
        s,
        "| Bits | Field | Type | Attributes | Description |\n|---|---|---|---|---|"
    );
    // Yüksek bitten düşüğe: donanım belgelerinin alışık olduğu sıra.
    for f in r.fields.iter().rev() {
        let bits = if f.width == 1 {
            f.lsb.to_string()
        } else {
            format!("{}:{}", f.msb(), f.lsb)
        };
        let mut attrs: Vec<&str> = Vec::new();
        if f.reserved {
            attrs.push("reserved");
        }
        if f.self_clearing {
            attrs.push("self-clearing");
        }
        if f.w1c {
            attrs.push("w1c");
        }
        let attrs = if attrs.is_empty() {
            "—".to_string()
        } else {
            attrs.join(", ")
        };
        let desc = if f.reserved {
            "Reads as 0; write 0.".to_string()
        } else {
            doc_summary(f.doc.as_deref())
        };
        let name = if f.reserved {
            "—".to_string()
        } else {
            format!("`{}`", f.name)
        };
        let _ = writeln!(
            s,
            "| {bits} | {name} | `{}` | {attrs} | {desc} |",
            volt_type(f)
        );
    }
    s.push('\n');
}
