//! `no_std` Rust sürücüsü (ADR-0053 §Rust).
//!
//! - Her erişim `core::ptr::{read_volatile, write_volatile}` ile 32
//!   bitlik sözcük üzerinden yapılır; `unsafe` yalnız `new` sözleşmesine
//!   dayanan iki özel yardımcıda toplanır.
//! - ReadOnly register'a setter, WriteOnly register'a getter ÜRETİLMEZ —
//!   yanlış yönde erişim derleme hatasıdır.
//! - `@reserved` bitler okumada maskelenir, yazmada 0 gider.
//! - `@self_clearing` alan `trigger_*`, `@w1c` alan `clear_*` metodu alır.
//! - Volt doc yorumları `///` olarak aktarılır.

use std::fmt::Write as _;

use volt_ast::mmio::{FieldDesc, FieldKind, RegAccess, RegDesc, RegMap};

use crate::check::{field_mask, reset_value};
use crate::names::{accessor, doc_lines, hex32_rust, hex_short, rmw_local, rust_type, upper_snake};
use crate::EmitOpts;

pub fn emit(map: &RegMap, opts: &EmitOpts) -> String {
    let mut s = crate::check::signature(map, opts);
    header(&mut s, map, opts);
    let _ = writeln!(s, "use core::ptr::{{read_volatile, write_volatile}};\n");
    doc_lines(&mut s, "", "///", map.doc.as_deref());
    if map.doc.is_none() {
        let _ = writeln!(s, "/// `{}` register block.", map.module);
    }
    let _ = writeln!(
        s,
        "#[derive(Debug)]\npub struct {} {{\n    base: *mut u32,\n}}\n\nimpl {} {{",
        map.module, map.module
    );
    constants(&mut s, map);
    constructors(&mut s, map);
    raw_helpers(&mut s);
    for reg in &map.registers {
        register(&mut s, reg);
    }
    s.push_str("}\n");
    s
}

fn header(s: &mut String, map: &RegMap, opts: &EmitOpts) {
    let _ = writeln!(
        s,
        "//! `{}` register map — generated by Volt HDL {} from `{}` (ADR-0053).\n\
         //! Do not edit: regenerate with `volt build --emit=rust {}`.\n\
         //!\n\
         //! `no_std`: only `core` is used. Every access is a 32-bit volatile\n\
         //! read or write of `base + offset` over `{}`.\n",
        map.module, opts.version, opts.source, opts.source, map.bus
    );
}

fn constants(s: &mut String, map: &RegMap) {
    let _ = writeln!(
        s,
        "    /// `@mmio(base = {})`.\n    pub const BASE: usize = {};",
        hex32_rust(map.base),
        hex32_rust(map.base)
    );
    for reg in &map.registers {
        let up = upper_snake(&reg.name);
        let _ = writeln!(
            s,
            "    /// `{}` register offset (`{}`{}).\n    pub const {up}_OFFSET: usize = {};",
            reg.name,
            access_name(reg.access),
            if reg.volatile { ", `volatile`" } else { "" },
            hex_short(reg.offset)
        );
        let _ = writeln!(
            s,
            "    /// Bits of `{}` that carry a field; reserved bits read as 0 and are written as 0.\n    \
             pub const {up}_MASK: u32 = {};",
            reg.name,
            hex32_rust(u64::from(reg.read_mask()))
        );
        let _ = writeln!(
            s,
            "    /// `{}` value after reset.\n    pub const {up}_RESET: u32 = {};",
            reg.name,
            hex32_rust(u64::from(reset_value(reg)))
        );
        for f in reg.named() {
            let fup = format!("{up}_{}", upper_snake(&f.name));
            let _ = writeln!(
                s,
                "    /// Lowest bit of `{}.{}`.\n    pub const {fup}_SHIFT: u32 = {};\n    \
                 /// Unshifted mask of `{}.{}`.\n    pub const {fup}_MASK: u32 = {};",
                reg.name,
                f.name,
                f.lsb,
                reg.name,
                f.name,
                hex32_rust(u64::from(field_mask(f.width)))
            );
        }
    }
}

fn constructors(s: &mut String, map: &RegMap) {
    let _ = writeln!(
        s,
        "\n    /// # Safety\n    \
         /// `base` must point to a mapped `{}` peripheral whose register layout\n    \
         /// matches this file, and the caller must guarantee exclusive access\n    \
         /// through this handle.\n    \
         #[must_use]\n    \
         pub const unsafe fn new(base: *mut u32) -> Self {{\n        Self {{ base }}\n    }}\n\n    \
         /// Handle at the default base address [`Self::BASE`].\n    \
         ///\n    \
         /// # Safety\n    \
         /// Same contract as [`Self::new`].\n    \
         #[must_use]\n    \
         pub unsafe fn at_default_base() -> Self {{\n        \
         // SAFETY: forwarded to the caller by this function's contract.\n        \
         unsafe {{ Self::new(core::ptr::without_provenance_mut(Self::BASE)) }}\n    }}\n",
        map.module
    );
}

fn raw_helpers(s: &mut String) {
    s.push_str(
        "    #[inline]\n    \
         fn read(&self, offset: usize) -> u32 {\n        \
         // SAFETY: `new` requires `base` to address a mapped peripheral.\n        \
         unsafe { read_volatile(self.base.byte_add(offset)) }\n    }\n\n    \
         #[inline]\n    \
         fn write(&mut self, offset: usize, value: u32) {\n        \
         // SAFETY: see `read`.\n        \
         unsafe { write_volatile(self.base.byte_add(offset), value) }\n    }\n",
    );
}

fn access_name(a: RegAccess) -> &'static str {
    match a {
        RegAccess::ReadWrite => "ReadWrite",
        RegAccess::ReadOnly => "ReadOnly",
        RegAccess::WriteOnly => "WriteOnly",
    }
}

fn register(s: &mut String, reg: &RegDesc) {
    let up = upper_snake(&reg.name);
    let _ = writeln!(
        s,
        "\n    // ── `{}` @ {} ({}{}) ──",
        reg.name,
        hex_short(reg.offset),
        access_name(reg.access),
        if reg.volatile { ", volatile" } else { "" }
    );
    if reg.access.readable() {
        doc_lines(s, "    ", "///", reg.doc.as_deref());
        let _ = writeln!(
            s,
            "    /// Raw `{}` word; reserved bits read as 0.\n    \
             #[must_use]\n    \
             pub fn {}_raw(&self) -> u32 {{\n        \
             self.read(Self::{up}_OFFSET) & Self::{up}_MASK\n    }}",
            reg.name, reg.name
        );
    }
    if reg.access.writable() {
        doc_lines(s, "    ", "///", reg.doc.as_deref());
        let _ = writeln!(
            s,
            "    /// Raw `{}` word; reserved bits are written as 0.\n    \
             pub fn set_{}_raw(&mut self, word: u32) {{\n        \
             self.write(Self::{up}_OFFSET, word & Self::{up}_MASK);\n    }}",
            reg.name, reg.name
        );
    }
    for field in reg.named() {
        field_methods(s, reg, field);
    }
}

/// Alanın sözcük içindeki değeri: `((word >> lsb) & mask) as T`.
fn extract(field: &FieldDesc, word: &str) -> String {
    let shifted = if field.lsb > 0 {
        format!("({word} >> {})", field.lsb)
    } else {
        word.to_string()
    };
    let masked = if field.width >= 32 {
        shifted
    } else {
        format!("({shifted} & 0x{:X})", (1u64 << field.width) - 1)
    };
    match field.kind {
        FieldKind::Bool => format!("{masked} != 0"),
        _ if field.width >= 32 => masked,
        _ => format!("{masked} as {}", rust_type(field)),
    }
}

/// Alan değerinin sözcükteki yeri: `(u32::from(v) << lsb) & fieldmask`
/// (dış parantezsiz — çağıran gerekirse sarar).
fn place(field: &FieldDesc, value: &str) -> String {
    let widened = format!("u32::from({value})");
    if field.width >= 32 {
        return widened;
    }
    let shifted = if field.lsb > 0 {
        format!("({widened} << {})", field.lsb)
    } else {
        widened
    };
    format!("{shifted} & {}", hex32_rust(u64::from(field.mask())))
}

/// Okuma-değiştirme-yazma gövdesi; korunacak bit yoksa okuma atlanır.
/// `local`: okunan sözcüğün yereli ([`rmw_local`] — setter parametresini
/// gölgelemez).
fn rmw_body(up: &str, keep: u32, placed: &str, local: &str) -> String {
    if keep == 0 {
        format!("self.write(Self::{up}_OFFSET, {placed});")
    } else {
        // Tek literal parantezsiz; ifade `|`'den ayrılsın diye sarılır.
        let rhs = if placed.contains(' ') {
            format!("({placed})")
        } else {
            placed.to_string()
        };
        format!(
            "let {local} = self.read(Self::{up}_OFFSET) & {};\n        \
             self.write(Self::{up}_OFFSET, {local} | {rhs});",
            hex32_rust(u64::from(keep))
        )
    }
}

/// Okuma-değiştirme-yazmada korunan bitler: adlandırılmış alanlar eksi
/// bu alan eksi `@self_clearing` bitler (yeniden tetiklenmesin).
fn keep_mask(reg: &RegDesc, field: &FieldDesc) -> u32 {
    let pulses = reg
        .named()
        .filter(|f| f.self_clearing || f.w1c)
        .fold(0, |m, f| m | f.mask());
    reg.read_mask() & !field.mask() & !pulses
}

fn field_methods(s: &mut String, reg: &RegDesc, field: &FieldDesc) {
    let acc = accessor(reg, field);
    let up = upper_snake(&reg.name);
    let ty = rust_type(field);
    let bit_doc = if field.width == 1 {
        format!("bit {}", field.lsb)
    } else {
        format!("bits {}:{}", field.msb(), field.lsb)
    };
    if reg.access.readable() {
        doc_lines(s, "    ", "///", field.doc.as_deref());
        let _ = writeln!(
            s,
            "    /// `{}.{}` ({bit_doc}){}.\n    \
             #[must_use]\n    \
             pub fn {acc}(&self) -> {ty} {{\n        {}\n    }}",
            reg.name,
            field.name,
            if reg.volatile {
                ", updated by hardware"
            } else {
                ""
            },
            extract(field, &format!("self.read(Self::{up}_OFFSET)"))
        );
    }
    if field.self_clearing {
        doc_lines(s, "    ", "///", field.doc.as_deref());
        let bit = hex32_rust(u64::from(field.mask()));
        let body = if reg.access.readable() {
            rmw_body(&up, keep_mask(reg, field), &bit, rmw_local(field))
        } else {
            format!("self.write(Self::{up}_OFFSET, {bit});")
        };
        let _ = writeln!(
            s,
            "    /// Pulse `{}.{}` (bit {}): self-clearing, high for one cycle.\n    \
             pub fn trigger_{acc}(&mut self) {{\n        {body}\n    }}",
            reg.name, field.name, field.lsb
        );
        return;
    }
    if field.w1c {
        doc_lines(s, "    ", "///", field.doc.as_deref());
        let _ = writeln!(
            s,
            "    /// Clear `{}.{}` (bit {}): write-1-to-clear, set by hardware.\n    \
             pub fn clear_{acc}(&mut self) {{\n        \
             self.write(Self::{up}_OFFSET, {});\n    }}",
            reg.name,
            field.name,
            field.lsb,
            hex32_rust(u64::from(field.mask()))
        );
        return;
    }
    if reg.access.writable() {
        doc_lines(s, "    ", "///", field.doc.as_deref());
        let body = if reg.access.readable() {
            rmw_body(
                &up,
                keep_mask(reg, field),
                &place(field, &field.name),
                rmw_local(field),
            )
        } else {
            format!(
                "// WriteOnly register: the other fields are written as 0.\n        \
                 self.write(Self::{up}_OFFSET, {});",
                place(field, &field.name)
            )
        };
        let _ = writeln!(
            s,
            "    /// Set `{}.{}` ({bit_doc}).\n    \
             pub fn set_{acc}(&mut self, {}: {ty}) {{\n        {body}\n    }}",
            reg.name, field.name, field.name
        );
    }
}
